// Copyright 2019-present Facebook
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package entdomain

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"text/template"

	"entgo.io/ent/entc/gen"
)

// protoMapperFileData holds all data needed to render a single entity's proto mapper file.
//
// Two rendering modes are supported:
//
//  1. Subpackage mode (default, !cfg.helpersInDomain):
//     Mappers and helpers live in {domain}/pbmap/ (package "pbmap").
//     Both domain and proto types are qualified (domain.User, entpb.User).
//     Helper functions are exported (PascalCase).
//
//  2. Domain mode (cfg.helpersInDomain):
//     Mappers and helpers live flat in the domain package.
//     Domain types are bare; proto types are qualified.
//     Helper functions are unexported (camelCase).
//     Mapper functions use method-receiver style: (d *User).ToProto().
type protoMapperFileData struct {
	PkgName        string
	EntityName     string
	ListName       string
	DomainGoImport string // Go import path for the domain package (subpkg mode only)
	DomainPkgAlias string // e.g. "domain" (subpkg mode only)
	ProtoGoImport  string // Go import path for the proto package
	ProtoPkgAlias  string // e.g. "entpb"
	Imports        []string
	IDField        protoMapperField
	Fields         []protoMapperField
	EnumHelpers    []protoEnumHelper
}

// protoMapperField describes one field in the proto mapper.
type protoMapperField struct {
	StructName     string
	ProtoFieldName string
	ToProtoExpr    string
	FromProtoExpr  string
}

// protoEnumHelper holds data for generating a pair of enum conversion functions.
// ProtoType, Unspecified, and ProtoConst store bare proto identifiers WITHOUT a
// package qualifier (e.g. "UserStatus", not "entpb.UserStatus"). Templates add
// the qualifier (ProtoPkgAlias) where needed.
type protoEnumHelper struct {
	ToFuncName         string
	FromFuncName       string
	DomainType         string // bare domain type, e.g. "UserStatus"
	ProtoType          string // bare proto type, e.g. "UserStatus"
	Unspecified        string // bare sentinel, e.g. "UserStatus_USER_STATUS_UNSPECIFIED"
	DefaultDomainConst string // e.g. "UserStatusActive"
	Cases              []protoEnumCase
}

type protoEnumCase struct {
	DomainConst string // e.g. "UserStatusActive"
	ProtoConst  string // bare, e.g. "UserStatus_USER_STATUS_ACTIVE"
}

// protoMapperSubpkgTmpl generates mapper functions for a sub-package (e.g. pbmap)
// that imports both the domain and proto packages.
// Both domain and proto types are fully qualified.
// Helper functions are exported (PascalCase) and local to this package.
var protoMapperSubpkgTmpl = template.Must(template.New("proto_mapper_subpkg").Parse(`// Code generated by entdomain, DO NOT EDIT.

package {{ .PkgName }}

import (
{{- range .Imports }}
	"{{ . }}"
{{- end }}
	{{ .DomainPkgAlias }} "{{ .DomainGoImport }}"
	{{ .ProtoPkgAlias }} "{{ .ProtoGoImport }}"
)
{{- range .EnumHelpers }}

func {{ .ToFuncName }}(s {{ $.DomainPkgAlias }}.{{ .DomainType }}) {{ $.ProtoPkgAlias }}.{{ .ProtoType }} {
	switch s {
{{- range .Cases }}
	case {{ $.DomainPkgAlias }}.{{ .DomainConst }}:
		return {{ $.ProtoPkgAlias }}.{{ .ProtoConst }}
{{- end }}
	default:
		return {{ $.ProtoPkgAlias }}.{{ .Unspecified }}
	}
}

func {{ .FromFuncName }}(s {{ $.ProtoPkgAlias }}.{{ .ProtoType }}) {{ $.DomainPkgAlias }}.{{ .DomainType }} {
	switch s {
{{- range .Cases }}
	case {{ $.ProtoPkgAlias }}.{{ .ProtoConst }}:
		return {{ $.DomainPkgAlias }}.{{ .DomainConst }}
{{- end }}
	default:
		return {{ $.DomainPkgAlias }}.{{ .DefaultDomainConst }}
	}
}
{{- end }}

// {{ .EntityName }}ToProto converts *{{ .DomainPkgAlias }}.{{ .EntityName }} to *{{ .ProtoPkgAlias }}.{{ .EntityName }}.
func {{ .EntityName }}ToProto(d *{{ .DomainPkgAlias }}.{{ .EntityName }}) *{{ .ProtoPkgAlias }}.{{ .EntityName }} {
	if d == nil {
		return nil
	}
	return &{{ .ProtoPkgAlias }}.{{ .EntityName }}{
		{{ .IDField.ProtoFieldName }}: {{ .IDField.ToProtoExpr }},
{{- range .Fields }}
		{{ .ProtoFieldName }}: {{ .ToProtoExpr }},
{{- end }}
	}
}

// {{ .EntityName }}FromProto converts *{{ .ProtoPkgAlias }}.{{ .EntityName }} to *{{ .DomainPkgAlias }}.{{ .EntityName }}.
func {{ .EntityName }}FromProto(p *{{ .ProtoPkgAlias }}.{{ .EntityName }}) *{{ .DomainPkgAlias }}.{{ .EntityName }} {
	if p == nil {
		return nil
	}
	return &{{ .DomainPkgAlias }}.{{ .EntityName }}{
		{{ .IDField.StructName }}: {{ .IDField.FromProtoExpr }},
{{- range .Fields }}
		{{ .StructName }}: {{ .FromProtoExpr }},
{{- end }}
	}
}

// {{ .EntityName }}ListToProto converts {{ .DomainPkgAlias }}.{{ .ListName }} to []*{{ .ProtoPkgAlias }}.{{ .EntityName }}.
func {{ .EntityName }}ListToProto(ds {{ .DomainPkgAlias }}.{{ .ListName }}) []*{{ .ProtoPkgAlias }}.{{ .EntityName }} {
	result := make([]*{{ .ProtoPkgAlias }}.{{ .EntityName }}, len(ds))
	for i, d := range ds {
		result[i] = {{ .EntityName }}ToProto(d)
	}
	return result
}

// {{ .EntityName }}ListFromProto converts []*{{ .ProtoPkgAlias }}.{{ .EntityName }} to {{ .DomainPkgAlias }}.{{ .ListName }}.
func {{ .EntityName }}ListFromProto(ps []*{{ .ProtoPkgAlias }}.{{ .EntityName }}) {{ .DomainPkgAlias }}.{{ .ListName }} {
	result := make({{ .DomainPkgAlias }}.{{ .ListName }}, len(ps))
	for i, p := range ps {
		result[i] = {{ .EntityName }}FromProto(p)
	}
	return result
}
`))

// protoMapperDomainTmpl generates mapper methods that live in the domain package.
// This is the legacy mode selected by WithProtoHelpersInDomain().
// Domain types are bare (same package); proto types use ProtoPkgAlias.
// Mapper functions use the method-receiver style: (d *User).ToProto().
var protoMapperDomainTmpl = template.Must(template.New("proto_mapper_domain").Parse(`// Code generated by entdomain, DO NOT EDIT.

package {{ .PkgName }}

import (
{{- range .Imports }}
	"{{ . }}"
{{- end }}
	{{ .ProtoPkgAlias }} "{{ .ProtoGoImport }}"
)
{{- range .EnumHelpers }}

func {{ .ToFuncName }}(s {{ .DomainType }}) {{ $.ProtoPkgAlias }}.{{ .ProtoType }} {
	switch s {
{{- range .Cases }}
	case {{ .DomainConst }}:
		return {{ $.ProtoPkgAlias }}.{{ .ProtoConst }}
{{- end }}
	default:
		return {{ $.ProtoPkgAlias }}.{{ .Unspecified }}
	}
}

func {{ .FromFuncName }}(s {{ $.ProtoPkgAlias }}.{{ .ProtoType }}) {{ .DomainType }} {
	switch s {
{{- range .Cases }}
	case {{ $.ProtoPkgAlias }}.{{ .ProtoConst }}:
		return {{ .DomainConst }}
{{- end }}
	default:
		return {{ .DefaultDomainConst }}
	}
}
{{- end }}

// ToProto converts *{{ .EntityName }} to *{{ .ProtoPkgAlias }}.{{ .EntityName }}.
func (d *{{ .EntityName }}) ToProto() *{{ .ProtoPkgAlias }}.{{ .EntityName }} {
	if d == nil {
		return nil
	}
	return &{{ .ProtoPkgAlias }}.{{ .EntityName }}{
		{{ .IDField.ProtoFieldName }}: {{ .IDField.ToProtoExpr }},
{{- range .Fields }}
		{{ .ProtoFieldName }}: {{ .ToProtoExpr }},
{{- end }}
	}
}

// {{ .EntityName }}FromProto converts *{{ .ProtoPkgAlias }}.{{ .EntityName }} to *{{ .EntityName }}.
func {{ .EntityName }}FromProto(p *{{ .ProtoPkgAlias }}.{{ .EntityName }}) *{{ .EntityName }} {
	if p == nil {
		return nil
	}
	return &{{ .EntityName }}{
		{{ .IDField.StructName }}: {{ .IDField.FromProtoExpr }},
{{- range .Fields }}
		{{ .StructName }}: {{ .FromProtoExpr }},
{{- end }}
	}
}

// ToProto converts {{ .ListName }} to []*{{ .ProtoPkgAlias }}.{{ .EntityName }}.
func (ds {{ .ListName }}) ToProto() []*{{ .ProtoPkgAlias }}.{{ .EntityName }} {
	result := make([]*{{ .ProtoPkgAlias }}.{{ .EntityName }}, len(ds))
	for i, d := range ds {
		result[i] = d.ToProto()
	}
	return result
}

// {{ .EntityName }}ListFromProto converts []*{{ .ProtoPkgAlias }}.{{ .EntityName }} to {{ .ListName }}.
func {{ .EntityName }}ListFromProto(ps []*{{ .ProtoPkgAlias }}.{{ .EntityName }}) {{ .ListName }} {
	result := make({{ .ListName }}, len(ps))
	for i, p := range ps {
		result[i] = {{ .EntityName }}FromProto(p)
	}
	return result
}
`))

// protoHelpersData is the template data for the proto helpers file.
type protoHelpersData struct {
	PkgName  string
	Exported bool // when true, functions have PascalCase names
}

var protoHelpersTmpl = template.Must(template.New("proto_helpers").Funcs(template.FuncMap{
	"fn": func(name string, exported bool) string {
		if exported {
			return strings.ToUpper(name[:1]) + name[1:]
		}
		return name
	},
}).Parse(`// Code generated by entdomain, DO NOT EDIT.

package {{ .PkgName }}

import (
	"time"

	"github.com/google/uuid"
	"google.golang.org/protobuf/types/known/durationpb"
	"google.golang.org/protobuf/types/known/structpb"
	"google.golang.org/protobuf/types/known/timestamppb"
)

// {{ fn "toInt64Slice" .Exported }} converts []int to []int64.
func {{ fn "toInt64Slice" .Exported }}(vs []int) []int64 {
	result := make([]int64, len(vs))
	for i, v := range vs {
		result[i] = int64(v)
	}
	return result
}

// {{ fn "fromInt64Slice" .Exported }} converts []int64 to []int.
func {{ fn "fromInt64Slice" .Exported }}(vs []int64) []int {
	result := make([]int, len(vs))
	for i, v := range vs {
		result[i] = int(v)
	}
	return result
}

// {{ fn "toInt64Ptr" .Exported }} converts *int to *int64.
func {{ fn "toInt64Ptr" .Exported }}(v *int) *int64 {
	if v == nil {
		return nil
	}
	n := int64(*v)
	return &n
}

// {{ fn "fromInt64Ptr" .Exported }} converts *int64 to *int.
func {{ fn "fromInt64Ptr" .Exported }}(v *int64) *int {
	if v == nil {
		return nil
	}
	n := int(*v)
	return &n
}

// {{ fn "toUint64Ptr" .Exported }} converts *uint to *uint64.
func {{ fn "toUint64Ptr" .Exported }}(v *uint) *uint64 {
	if v == nil {
		return nil
	}
	n := uint64(*v)
	return &n
}

// {{ fn "fromUint64Ptr" .Exported }} converts *uint64 to *uint.
func {{ fn "fromUint64Ptr" .Exported }}(v *uint64) *uint {
	if v == nil {
		return nil
	}
	n := uint(*v)
	return &n
}

// {{ fn "timeToTimestampProto" .Exported }} converts *time.Time to *timestamppb.Timestamp.
func {{ fn "timeToTimestampProto" .Exported }}(v *time.Time) *timestamppb.Timestamp {
	if v == nil {
		return nil
	}
	return timestamppb.New(*v)
}

// {{ fn "timestampProtoToTime" .Exported }} converts *timestamppb.Timestamp to *time.Time.
func {{ fn "timestampProtoToTime" .Exported }}(v *timestamppb.Timestamp) *time.Time {
	if v == nil {
		return nil
	}
	t := v.AsTime()
	return &t
}

// {{ fn "durationToDurationProto" .Exported }} converts *time.Duration to *durationpb.Duration.
func {{ fn "durationToDurationProto" .Exported }}(v *time.Duration) *durationpb.Duration {
	if v == nil {
		return nil
	}
	return durationpb.New(*v)
}

// {{ fn "durationProtoToDuration" .Exported }} converts *durationpb.Duration to *time.Duration.
func {{ fn "durationProtoToDuration" .Exported }}(v *durationpb.Duration) *time.Duration {
	if v == nil {
		return nil
	}
	d := v.AsDuration()
	return &d
}

// {{ fn "uuidPtrToProtoString" .Exported }} converts *uuid.UUID to *string.
func {{ fn "uuidPtrToProtoString" .Exported }}(v *uuid.UUID) *string {
	if v == nil {
		return nil
	}
	s := v.String()
	return &s
}

// {{ fn "protoStringToUUIDPtr" .Exported }} converts *string to *uuid.UUID.
func {{ fn "protoStringToUUIDPtr" .Exported }}(v *string) *uuid.UUID {
	if v == nil {
		return nil
	}
	id := uuid.MustParse(*v)
	return &id
}

// {{ fn "uuidSliceToStringSlice" .Exported }} converts []uuid.UUID to []string.
func {{ fn "uuidSliceToStringSlice" .Exported }}(vs []uuid.UUID) []string {
	result := make([]string, len(vs))
	for i, v := range vs {
		result[i] = v.String()
	}
	return result
}

// {{ fn "stringSliceToUUIDSlice" .Exported }} converts []string to []uuid.UUID.
func {{ fn "stringSliceToUUIDSlice" .Exported }}(vs []string) []uuid.UUID {
	result := make([]uuid.UUID, len(vs))
	for i, v := range vs {
		result[i] = uuid.MustParse(v)
	}
	return result
}

// {{ fn "mapToProtoStruct" .Exported }} converts map[string]any to *structpb.Struct.
func {{ fn "mapToProtoStruct" .Exported }}(m map[string]any) *structpb.Struct {
	if m == nil {
		return nil
	}
	s, _ := structpb.NewStruct(m)
	return s
}

// {{ fn "protoStructToMap" .Exported }} converts *structpb.Struct to map[string]any.
func {{ fn "protoStructToMap" .Exported }}(s *structpb.Struct) map[string]any {
	if s == nil {
		return nil
	}
	return s.AsMap()
}

`))

// protoHelperFuncNames lists all helper function names (unexported/camelCase form).
// Used to detect helper calls in generated expressions and adjust their casing.
var protoHelperFuncNames = []string{
	"toInt64Ptr", "fromInt64Ptr",
	"toInt64Slice", "fromInt64Slice",
	"toUint64Ptr", "fromUint64Ptr",
	"timeToTimestampProto", "timestampProtoToTime",
	"durationToDurationProto", "durationProtoToDuration",
	"uuidPtrToProtoString", "protoStringToUUIDPtr",
	"uuidSliceToStringSlice", "stringSliceToUUIDSlice",
	"mapToProtoStruct", "protoStructToMap",
}

// generateProtoMapperFiles generates the proto mapper files for each entity.
//
// Default (cfg.helpersInDomain=false): mapper + helpers live in {domain}/pbmap/ subpackage.
// Both domain and proto types are qualified; helper functions are exported.
//
// With WithProtoHelpersInDomain(): mapper + helpers live in the domain package.
// Domain types are bare; mapper functions use method-receiver style.
func generateProtoMapperFiles(g *gen.Graph, cfg *ProtoConfig, outDir, domainPkgPath, domainPkgName string) error {
	protoGoImport, protoPkgAlias := parseGoPackage(cfg.goPackage)
	if protoPkgAlias == "" {
		protoPkgAlias = cfg.pkgName
	}

	var mapperOutDir string
	var mapperPkgName string
	var domainGoImport string
	var tmpl *template.Template
	helpersExported := !cfg.helpersInDomain

	if cfg.helpersInDomain {
		// Legacy domain mode: flat in the domain package, method-receiver style.
		mapperOutDir = filepath.Join(outDir, domainPkgPath)
		mapperPkgName = domainPkgName
		tmpl = protoMapperDomainTmpl
	} else {
		// Default: pbmap subpackage nested under the domain directory.
		mapperOutDir = filepath.Join(outDir, domainPkgPath, "pbmap")
		mapperPkgName = "pbmap"
		tmpl = protoMapperSubpkgTmpl
		var err error
		domainGoImport, err = resolveGoImportPath(g, domainPkgPath)
		if err != nil {
			return fmt.Errorf("entdomain proto mapper: resolve domain import path: %w", err)
		}
	}

	if err := os.MkdirAll(mapperOutDir, 0755); err != nil {
		return fmt.Errorf("entdomain proto mapper: create output dir: %w", err)
	}

	hasHelpers := false

	for _, t := range g.Nodes {
		ant, err := extractEntityAnnotation(t.Annotations)
		if err != nil {
			return fmt.Errorf("entdomain proto mapper: extract annotation for %s: %w", t.Name, err)
		}
		if ant == nil {
			continue
		}

		data, needsHelpers, buildErr := buildProtoMapperFileData(
			t, ant,
			mapperPkgName, protoGoImport, protoPkgAlias,
			domainGoImport, domainPkgName,
			helpersExported,
		)
		if buildErr != nil {
			return fmt.Errorf("entdomain proto mapper: build data for %s: %w", t.Name, buildErr)
		}
		if needsHelpers {
			hasHelpers = true
		}

		src, renderErr := renderProtoMapperFile(data, tmpl)
		if renderErr != nil {
			return fmt.Errorf("entdomain proto mapper: render file for %s: %w", t.Name, renderErr)
		}

		outPath := filepath.Join(mapperOutDir, strings.ToLower(t.Name)+"_proto_gen.go")
		if err := os.WriteFile(outPath, src, 0644); err != nil {
			return fmt.Errorf("entdomain proto mapper: write file %s: %w", outPath, err)
		}
	}

	if hasHelpers {
		if err := generateProtoHelpersFile(mapperOutDir, mapperPkgName, helpersExported); err != nil {
			return fmt.Errorf("entdomain proto mapper: generate helpers: %w", err)
		}
	}

	return nil
}

// buildProtoMapperFileData constructs the template data for a single entity's proto mapper file.
// helpersExported controls whether helper function calls use PascalCase (true, subpkg mode)
// or camelCase (false, domain mode).
func buildProtoMapperFileData(
	t *gen.Type, ant *EntityAnnotation,
	pkgName, protoGoImport, protoPkgAlias string,
	domainGoImport, domainPkgAlias string,
	helpersExported bool,
) (*protoMapperFileData, bool, error) {
	needsHelpers := false
	goImports := map[string]bool{}

	data := &protoMapperFileData{
		PkgName:        pkgName,
		EntityName:     t.Name,
		ListName:       t.Name + "List",
		DomainGoImport: domainGoImport,
		DomainPkgAlias: domainPkgAlias,
		ProtoGoImport:  protoGoImport,
		ProtoPkgAlias:  protoPkgAlias,
	}

	// ID field.
	idSpec := resolveEntFieldProtoSpec(t.Name, t.ID, nil)
	rawIDTo := applyExprTemplate(idSpec.ToProtoExpr, "d.ID")
	rawIDFrom := applyExprTemplate(idSpec.FromProtoExpr, "p.Id")
	trackExprImports(rawIDTo, rawIDFrom, goImports)
	if isHelperExpr(rawIDTo) || isHelperExpr(rawIDFrom) {
		needsHelpers = true
	}
	data.IDField = protoMapperField{
		StructName:     "ID",
		ProtoFieldName: "Id",
		ToProtoExpr:    adjustHelperExpr(rawIDTo, helpersExported),
		FromProtoExpr:  adjustHelperExpr(rawIDFrom, helpersExported),
	}

	// Regular fields.
	for _, f := range t.Fields {
		if f.IsEdgeField() {
			continue
		}
		fa, err := extractFieldAnnotation(f.Annotations)
		if err != nil {
			return nil, false, fmt.Errorf("extract field annotation for %s: %w", f.Name, err)
		}
		if fa != nil && fa.SkipProto {
			continue
		}

		spec := resolveEntFieldProtoSpec(t.Name, f, fa)
		if spec.IsExcluded {
			continue
		}

		protoGoName := protoPascal(f.Name)
		domainExpr := "d." + f.StructField()
		protoExpr := "p." + protoGoName

		mf := protoMapperField{
			StructName:     f.StructField(),
			ProtoFieldName: protoGoName,
		}

		if spec.IsEnum {
			toHelperName := strings.ToLower(t.Name[:1]) + t.Name[1:] + pascal(f.Name) + "ToProto"
			fromHelperName := strings.ToLower(t.Name[:1]) + t.Name[1:] + pascal(f.Name) + "FromProto"
			mf.ToProtoExpr = toHelperName + "(" + domainExpr + ")"
			mf.FromProtoExpr = fromHelperName + "(" + protoExpr + ")"

			// Enum helper: store bare proto identifiers (no package qualifier).
			prefix := strings.ToUpper(snake(t.Name)) + "_" + strings.ToUpper(snake(f.StructField()))
			enumType := t.Name + f.StructField()
			helper := protoEnumHelper{
				ToFuncName:   toHelperName,
				FromFuncName: fromHelperName,
				DomainType:   enumType,
				ProtoType:    enumType,
				Unspecified:  enumType + "_" + prefix + "_UNSPECIFIED",
			}
			defaultSet := false
			for _, v := range f.Enums {
				domainConst := enumType + pascal(v.Value)
				protoConst := enumType + "_" + prefix + "_" + strings.ToUpper(snake(v.Value))
				helper.Cases = append(helper.Cases, protoEnumCase{
					DomainConst: domainConst,
					ProtoConst:  protoConst,
				})
				if !defaultSet {
					helper.DefaultDomainConst = domainConst
					defaultSet = true
				}
			}
			data.EnumHelpers = append(data.EnumHelpers, helper)
		} else {
			rawTo := applyExprTemplate(spec.ToProtoExpr, domainExpr)
			rawFrom := applyExprTemplate(spec.FromProtoExpr, protoExpr)
			trackExprImports(rawTo, rawFrom, goImports)
			if isHelperExpr(rawTo) || isHelperExpr(rawFrom) {
				needsHelpers = true
			}
			mf.ToProtoExpr = adjustHelperExpr(rawTo, helpersExported)
			mf.FromProtoExpr = adjustHelperExpr(rawFrom, helpersExported)
		}

		data.Fields = append(data.Fields, mf)
	}

	// Edge fields.
	for _, e := range t.Edges {
		ea, err := extractEdgeAnnotation(e.Annotations)
		if err != nil {
			return nil, false, fmt.Errorf("extract edge annotation for %s: %w", e.Name, err)
		}
		if ea == nil {
			continue
		}
		fa, err := extractFieldAnnotation(e.Annotations)
		if err != nil {
			return nil, false, fmt.Errorf("extract field annotation for edge %s: %w", e.Name, err)
		}

		specs := resolveEdgeProtoSpec(e, ea, fa)
		specIdx := 0

		if ea.HasIDs() && specIdx < len(specs) {
			spec := specs[specIdx]
			specIdx++
			if !spec.IsExcluded {
				var domainFieldName, protoFieldName string
				if e.Unique {
					domainFieldName = pascal(e.Name) + "ID"
					protoFieldName = pascal(e.Name) + "Id"
				} else {
					domainFieldName = singular(pascal(e.Name)) + "IDs"
					protoFieldName = pascal(singular(e.Name)) + "Ids"
				}

				domainExpr := "d." + domainFieldName
				protoExpr := "p." + protoFieldName

				rawTo := applyExprTemplate(spec.ToProtoExpr, domainExpr)
				rawFrom := applyExprTemplate(spec.FromProtoExpr, protoExpr)

				mf := protoMapperField{
					StructName:     domainFieldName,
					ProtoFieldName: protoFieldName,
					ToProtoExpr:    adjustHelperExpr(rawTo, helpersExported),
					FromProtoExpr:  adjustHelperExpr(rawFrom, helpersExported),
				}

				if spec.IsRepeated && spec.ProtoType == "int64" {
					rawTo = "toInt64Slice(" + domainExpr + ")"
					rawFrom = "fromInt64Slice(" + protoExpr + ")"
					mf.ToProtoExpr = adjustHelperExpr(rawTo, helpersExported)
					mf.FromProtoExpr = adjustHelperExpr(rawFrom, helpersExported)
					needsHelpers = true
				}

				// Track imports and helpers from raw (pre-capitalization) expressions.
				trackExprImports(rawTo, rawFrom, goImports)
				if isHelperExpr(rawTo) || isHelperExpr(rawFrom) {
					needsHelpers = true
				}

				data.Fields = append(data.Fields, mf)
			}
		}

		if ea.HasNest() && specIdx < len(specs) {
			spec := specs[specIdx]
			specIdx++
			if !spec.IsExcluded {
				entityName := spec.NestEntityName
				domainFieldName := pascal(e.Name)
				protoFieldName := protoPascal(e.Name)
				domainExpr := "d." + domainFieldName
				protoExpr := "p." + protoFieldName

				var rawTo, rawFrom string
				if spec.IsRepeated {
					if helpersExported {
						// Subpackage mode: standalone functions in same pbmap package.
						rawTo = entityName + "ListToProto(" + domainExpr + ")"
						rawFrom = entityName + "ListFromProto(" + protoExpr + ")"
					} else {
						// Domain mode: slice has ToProto() method; FromProto is standalone.
						rawTo = domainExpr + ".ToProto()"
						rawFrom = entityName + "ListFromProto(" + protoExpr + ")"
					}
				} else {
					if helpersExported {
						rawTo = entityName + "ToProto(" + domainExpr + ")"
						rawFrom = entityName + "FromProto(" + protoExpr + ")"
					} else {
						rawTo = domainExpr + ".ToProto()"
						rawFrom = entityName + "FromProto(" + protoExpr + ")"
					}
				}

				data.Fields = append(data.Fields, protoMapperField{
					StructName:     domainFieldName,
					ProtoFieldName: protoFieldName,
					ToProtoExpr:    rawTo,
					FromProtoExpr:  rawFrom,
				})
			}
		}
	}

	// Virtual fields.
	for _, vf := range ant.VirtualFields {
		spec := resolveVirtualFieldProtoSpec(vf)
		if spec.IsExcluded {
			continue
		}

		protoGoName := protoPascal(vf.Name)
		domainExpr := "d." + pascal(vf.Name)
		protoExpr := "p." + protoGoName

		rawTo := applyExprTemplate(spec.ToProtoExpr, domainExpr)
		rawFrom := applyExprTemplate(spec.FromProtoExpr, protoExpr)
		trackExprImports(rawTo, rawFrom, goImports)
		if isHelperExpr(rawTo) || isHelperExpr(rawFrom) {
			needsHelpers = true
		}

		data.Fields = append(data.Fields, protoMapperField{
			StructName:     pascal(vf.Name),
			ProtoFieldName: protoGoName,
			ToProtoExpr:    adjustHelperExpr(rawTo, helpersExported),
			FromProtoExpr:  adjustHelperExpr(rawFrom, helpersExported),
		})
	}

	for imp := range goImports {
		data.Imports = append(data.Imports, imp)
	}
	sort.Strings(data.Imports)

	return data, needsHelpers, nil
}

// generateProtoHelpersFile writes proto_helpers_gen.go to outDir.
// When exported is true the functions have PascalCase names.
func generateProtoHelpersFile(outDir string, pkgName string, exported bool) error {
	if err := os.MkdirAll(outDir, 0755); err != nil {
		return fmt.Errorf("create helpers dir: %w", err)
	}
	var buf bytes.Buffer
	if err := protoHelpersTmpl.Execute(&buf, protoHelpersData{PkgName: pkgName, Exported: exported}); err != nil {
		return fmt.Errorf("execute helpers template: %w", err)
	}
	src, err := format.Source(buf.Bytes())
	if err != nil {
		return fmt.Errorf("format helpers source (raw: %s): %w", buf.String(), err)
	}
	return os.WriteFile(filepath.Join(outDir, "proto_helpers_gen.go"), src, 0644)
}

// renderProtoMapperFile renders the given proto mapper template and gofmts the result.
func renderProtoMapperFile(data *protoMapperFileData, tmpl *template.Template) ([]byte, error) {
	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return nil, fmt.Errorf("execute proto mapper template: %w", err)
	}
	src, err := format.Source(buf.Bytes())
	if err != nil {
		return nil, fmt.Errorf("format proto mapper source for %s (raw:\n%s\n): %w", data.EntityName, buf.String(), err)
	}
	return src, nil
}

// applyExprTemplate substitutes %s in the format template with value.
// If template is empty, returns value directly.
func applyExprTemplate(tmpl, value string) string {
	if tmpl == "" {
		return value
	}
	return fmt.Sprintf(tmpl, value)
}

// isHelperExpr reports whether expr begins with a call to a known proto helper function.
func isHelperExpr(expr string) bool {
	for _, name := range protoHelperFuncNames {
		if strings.HasPrefix(expr, name+"(") {
			return true
		}
	}
	return false
}

// adjustHelperExpr capitalizes the first letter of a known helper function call
// when capitalize is true (helpers are exported). E.g.:
//
//	"toInt64Ptr(d.Score)" → "ToInt64Ptr(d.Score)" when capitalize=true
func adjustHelperExpr(expr string, capitalize bool) string {
	if !capitalize || expr == "" {
		return expr
	}
	for _, name := range protoHelperFuncNames {
		if strings.HasPrefix(expr, name+"(") {
			return strings.ToUpper(name[:1]) + expr[1:]
		}
	}
	return expr
}

// trackExprImports inspects a ToProto/FromProto expression pair and records
// any Go package imports they require into goImports.
func trackExprImports(rawTo, rawFrom string, goImports map[string]bool) {
	for _, expr := range [2]string{rawTo, rawFrom} {
		if strings.Contains(expr, "timestamppb") {
			goImports["google.golang.org/protobuf/types/known/timestamppb"] = true
		}
		if strings.Contains(expr, "durationpb") {
			goImports["google.golang.org/protobuf/types/known/durationpb"] = true
		}
		if strings.Contains(expr, "uuid.MustParse") || strings.Contains(expr, "uuid.UUID") {
			goImports["github.com/google/uuid"] = true
		}
		if strings.Contains(expr, "structpb") {
			goImports["google.golang.org/protobuf/types/known/structpb"] = true
		}
	}
}

// protoPascal converts a snake_case field name to the Go struct field name as
// generated by protoc-gen-go. Unlike ent's pascal(), it does NOT treat "id" as
// an acronym: "external_id" → "ExternalId" (not "ExternalID").
func protoPascal(s string) string {
	parts := strings.Split(s, "_")
	for i, p := range parts {
		if len(p) > 0 {
			parts[i] = strings.ToUpper(p[:1]) + p[1:]
		}
	}
	return strings.Join(parts, "")
}

// parseGoPackage splits "import/path;alias" into import path and alias.
func parseGoPackage(goPackage string) (importPath, alias string) {
	parts := strings.SplitN(goPackage, ";", 2)
	importPath = parts[0]
	if len(parts) == 2 {
		alias = parts[1]
	}
	return
}

// resolveGoImportPath derives the Go import path for a package whose filesystem
// location is relPkgPath relative to moduleRoot(g) (i.e. filepath.Dir(g.Config.Target)).
// It walks up from the ent target directory to find go.mod.
func resolveGoImportPath(g *gen.Graph, relPkgPath string) (string, error) {
	outDir := moduleRoot(g)
	pkgAbsPath := filepath.Join(outDir, relPkgPath)

	dir := outDir
	for {
		data, err := os.ReadFile(filepath.Join(dir, "go.mod"))
		if err == nil {
			for line := range strings.SplitSeq(string(data), "\n") {
				line = strings.TrimSpace(line)
				if after, ok := strings.CutPrefix(line, "module "); ok {
					moduleName := strings.TrimSpace(after)
					rel, relErr := filepath.Rel(dir, pkgAbsPath)
					if relErr != nil {
						return "", relErr
					}
					return moduleName + "/" + filepath.ToSlash(rel), nil
				}
			}
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			break
		}
		dir = parent
	}
	return "", fmt.Errorf("go.mod not found starting from %s", outDir)
}
