// Code generated by entdomain, DO NOT EDIT.

package pbmap

import (
	domain "github.com/danhtran94/entdomain/internal/testdata/domain"
	entpb "github.com/danhtran94/entdomain/internal/testdata/proto/entpb"
	"google.golang.org/protobuf/types/known/timestamppb"
)

func userStatusToProto(s domain.UserStatus) entpb.UserStatus {
	switch s {
	case domain.UserStatusActive:
		return entpb.UserStatus_USER_STATUS_ACTIVE
	case domain.UserStatusInactive:
		return entpb.UserStatus_USER_STATUS_INACTIVE
	default:
		return entpb.UserStatus_USER_STATUS_UNSPECIFIED
	}
}

func userStatusFromProto(s entpb.UserStatus) domain.UserStatus {
	switch s {
	case entpb.UserStatus_USER_STATUS_ACTIVE:
		return domain.UserStatusActive
	case entpb.UserStatus_USER_STATUS_INACTIVE:
		return domain.UserStatusInactive
	default:
		return domain.UserStatusActive
	}
}

// UserToProto converts *domain.User to *entpb.User.
func UserToProto(d *domain.User) *entpb.User {
	if d == nil {
		return nil
	}
	return &entpb.User{
		Id:        int64(d.ID),
		Name:      d.Name,
		Bio:       d.Bio,
		Status:    userStatusToProto(d.Status),
		CreatedAt: timestamppb.New(d.CreatedAt),
		Score:     ToInt64Ptr(d.Score),
		PostIds:   ToInt64Slice(d.PostIDs),
		FullName:  d.FullName,
		IsPremium: d.IsPremium,
		ExpiresAt: timestamppb.New(d.ExpiresAt),
	}
}

// UserFromProto converts *entpb.User to *domain.User.
func UserFromProto(p *entpb.User) *domain.User {
	if p == nil {
		return nil
	}
	return &domain.User{
		ID:        int(p.Id),
		Name:      p.Name,
		Bio:       p.Bio,
		Status:    userStatusFromProto(p.Status),
		CreatedAt: p.CreatedAt.AsTime(),
		Score:     FromInt64Ptr(p.Score),
		PostIDs:   FromInt64Slice(p.PostIds),
		FullName:  p.FullName,
		IsPremium: p.IsPremium,
		ExpiresAt: p.ExpiresAt.AsTime(),
	}
}

// UserListToProto converts domain.UserList to []*entpb.User.
func UserListToProto(ds domain.UserList) []*entpb.User {
	result := make([]*entpb.User, len(ds))
	for i, d := range ds {
		result[i] = UserToProto(d)
	}
	return result
}

// UserListFromProto converts []*entpb.User to domain.UserList.
func UserListFromProto(ps []*entpb.User) domain.UserList {
	result := make(domain.UserList, len(ps))
	for i, p := range ps {
		result[i] = UserFromProto(p)
	}
	return result
}
