// Code generated by entdomain, DO NOT EDIT.

package pbmap

import (
	domain "github.com/danhtran94/entdomain/examples/basic/domain"
	entpb "github.com/danhtran94/entdomain/examples/basic/proto/entpb"
)

// PostToProto converts *domain.Post to *entpb.Post.
func PostToProto(d *domain.Post) *entpb.Post {
	if d == nil {
		return nil
	}
	return &entpb.Post{
		Id:        int64(d.ID),
		Title:     d.Title,
		Published: d.Published,
		OwnerId:   int64(d.OwnerID),
		PinnerIds: ToInt64Slice(d.PinnerIDs),
	}
}

// PostFromProto converts *entpb.Post to *domain.Post.
func PostFromProto(p *entpb.Post) *domain.Post {
	if p == nil {
		return nil
	}
	return &domain.Post{
		ID:        int(p.Id),
		Title:     p.Title,
		Published: p.Published,
		OwnerID:   int(p.OwnerId),
		PinnerIDs: FromInt64Slice(p.PinnerIds),
	}
}

// PostListToProto converts domain.PostList to []*entpb.Post.
func PostListToProto(ds domain.PostList) []*entpb.Post {
	result := make([]*entpb.Post, len(ds))
	for i, d := range ds {
		result[i] = PostToProto(d)
	}
	return result
}

// PostListFromProto converts []*entpb.Post to domain.PostList.
func PostListFromProto(ps []*entpb.Post) domain.PostList {
	result := make(domain.PostList, len(ps))
	for i, p := range ps {
		result[i] = PostFromProto(p)
	}
	return result
}
