// Code generated by entdomain, DO NOT EDIT.

package pbmap

import (
	"time"

	"github.com/google/uuid"
	"google.golang.org/protobuf/types/known/durationpb"
	"google.golang.org/protobuf/types/known/structpb"
	"google.golang.org/protobuf/types/known/timestamppb"
)

// ToInt64Slice converts []int to []int64.
func ToInt64Slice(vs []int) []int64 {
	result := make([]int64, len(vs))
	for i, v := range vs {
		result[i] = int64(v)
	}
	return result
}

// FromInt64Slice converts []int64 to []int.
func FromInt64Slice(vs []int64) []int {
	result := make([]int, len(vs))
	for i, v := range vs {
		result[i] = int(v)
	}
	return result
}

// ToInt64Ptr converts *int to *int64.
func ToInt64Ptr(v *int) *int64 {
	if v == nil {
		return nil
	}
	n := int64(*v)
	return &n
}

// FromInt64Ptr converts *int64 to *int.
func FromInt64Ptr(v *int64) *int {
	if v == nil {
		return nil
	}
	n := int(*v)
	return &n
}

// ToUint64Ptr converts *uint to *uint64.
func ToUint64Ptr(v *uint) *uint64 {
	if v == nil {
		return nil
	}
	n := uint64(*v)
	return &n
}

// FromUint64Ptr converts *uint64 to *uint.
func FromUint64Ptr(v *uint64) *uint {
	if v == nil {
		return nil
	}
	n := uint(*v)
	return &n
}

// TimeToTimestampProto converts *time.Time to *timestamppb.Timestamp.
func TimeToTimestampProto(v *time.Time) *timestamppb.Timestamp {
	if v == nil {
		return nil
	}
	return timestamppb.New(*v)
}

// TimestampProtoToTime converts *timestamppb.Timestamp to *time.Time.
func TimestampProtoToTime(v *timestamppb.Timestamp) *time.Time {
	if v == nil {
		return nil
	}
	t := v.AsTime()
	return &t
}

// DurationToDurationProto converts *time.Duration to *durationpb.Duration.
func DurationToDurationProto(v *time.Duration) *durationpb.Duration {
	if v == nil {
		return nil
	}
	return durationpb.New(*v)
}

// DurationProtoToDuration converts *durationpb.Duration to *time.Duration.
func DurationProtoToDuration(v *durationpb.Duration) *time.Duration {
	if v == nil {
		return nil
	}
	d := v.AsDuration()
	return &d
}

// UuidPtrToProtoString converts *uuid.UUID to *string.
func UuidPtrToProtoString(v *uuid.UUID) *string {
	if v == nil {
		return nil
	}
	s := v.String()
	return &s
}

// ProtoStringToUUIDPtr converts *string to *uuid.UUID.
func ProtoStringToUUIDPtr(v *string) *uuid.UUID {
	if v == nil {
		return nil
	}
	id := uuid.MustParse(*v)
	return &id
}

// UuidSliceToStringSlice converts []uuid.UUID to []string.
func UuidSliceToStringSlice(vs []uuid.UUID) []string {
	result := make([]string, len(vs))
	for i, v := range vs {
		result[i] = v.String()
	}
	return result
}

// StringSliceToUUIDSlice converts []string to []uuid.UUID.
func StringSliceToUUIDSlice(vs []string) []uuid.UUID {
	result := make([]uuid.UUID, len(vs))
	for i, v := range vs {
		result[i] = uuid.MustParse(v)
	}
	return result
}

// MapToProtoStruct converts map[string]any to *structpb.Struct.
func MapToProtoStruct(m map[string]any) *structpb.Struct {
	if m == nil {
		return nil
	}
	s, _ := structpb.NewStruct(m)
	return s
}

// ProtoStructToMap converts *structpb.Struct to map[string]any.
func ProtoStructToMap(s *structpb.Struct) map[string]any {
	if s == nil {
		return nil
	}
	return s.AsMap()
}
