// Code generated by entdomain, DO NOT EDIT.

package pbmap

import (
	domain "github.com/danhtran94/entdomain/examples/basic/domain"
	entpb "github.com/danhtran94/entdomain/examples/basic/proto/entpb"
)

// TagToProto converts *domain.Tag to *entpb.Tag.
func TagToProto(d *domain.Tag) *entpb.Tag {
	if d == nil {
		return nil
	}
	return &entpb.Tag{
		Id:      int64(d.ID),
		Name:    d.Name,
		UserIds: ToInt64Slice(d.UserIDs),
		Users:   UserListToProto(d.Users),
	}
}

// TagFromProto converts *entpb.Tag to *domain.Tag.
func TagFromProto(p *entpb.Tag) *domain.Tag {
	if p == nil {
		return nil
	}
	return &domain.Tag{
		ID:      int(p.Id),
		Name:    p.Name,
		UserIDs: FromInt64Slice(p.UserIds),
		Users:   UserListFromProto(p.Users),
	}
}

// TagListToProto converts domain.TagList to []*entpb.Tag.
func TagListToProto(ds domain.TagList) []*entpb.Tag {
	result := make([]*entpb.Tag, len(ds))
	for i, d := range ds {
		result[i] = TagToProto(d)
	}
	return result
}

// TagListFromProto converts []*entpb.Tag to domain.TagList.
func TagListFromProto(ps []*entpb.Tag) domain.TagList {
	result := make(domain.TagList, len(ps))
	for i, p := range ps {
		result[i] = TagFromProto(p)
	}
	return result
}
