// Code generated by entdomain, DO NOT EDIT.

package pbmap

import (
	domain "github.com/danhtran94/entdomain/examples/basic/domain"
	entpb "github.com/danhtran94/entdomain/examples/basic/proto/entpb"
	"github.com/google/uuid"
	"google.golang.org/protobuf/types/known/durationpb"
	"google.golang.org/protobuf/types/known/timestamppb"
)

func userStatusToProto(s domain.UserStatus) entpb.UserStatus {
	switch s {
	case domain.UserStatusActive:
		return entpb.UserStatus_USER_STATUS_ACTIVE
	case domain.UserStatusInactive:
		return entpb.UserStatus_USER_STATUS_INACTIVE
	default:
		return entpb.UserStatus_USER_STATUS_UNSPECIFIED
	}
}

func userStatusFromProto(s entpb.UserStatus) domain.UserStatus {
	switch s {
	case entpb.UserStatus_USER_STATUS_ACTIVE:
		return domain.UserStatusActive
	case entpb.UserStatus_USER_STATUS_INACTIVE:
		return domain.UserStatusInactive
	default:
		return domain.UserStatusActive
	}
}

// UserToProto converts *domain.User to *entpb.User.
func UserToProto(d *domain.User) *entpb.User {
	if d == nil {
		return nil
	}
	return &entpb.User{
		Id:                   int64(d.ID),
		Name:                 d.Name,
		Bio:                  d.Bio,
		Status:               userStatusToProto(d.Status),
		CreatedAt:            timestamppb.New(d.CreatedAt),
		Score:                ToInt64Ptr(d.Score),
		ExternalId:           d.ExternalID.String(),
		UpdatedAt:            TimeToTimestampProto(d.UpdatedAt),
		Settings:             MapToProtoStruct(d.Settings),
		Labels:               MapToProtoStruct(d.Labels),
		TagNames:             d.TagNames,
		Metadata:             UserMetadataToProto(d.Metadata),
		PostIds:              ToInt64Slice(d.PostIDs),
		Posts:                PostListToProto(d.Posts),
		PinnedPostId:         int64(d.PinnedPostID),
		PinnedPost:           PostToProto(d.PinnedPost),
		TagIds:               ToInt64Slice(d.TagIDs),
		Tags:                 TagListToProto(d.Tags),
		FullName:             d.FullName,
		IsPremium:            d.IsPremium,
		ExpiresAt:            timestamppb.New(d.ExpiresAt),
		SubscriptionDuration: durationpb.New(d.SubscriptionDuration),
	}
}

// UserFromProto converts *entpb.User to *domain.User.
func UserFromProto(p *entpb.User) *domain.User {
	if p == nil {
		return nil
	}
	return &domain.User{
		ID:                   int(p.Id),
		Name:                 p.Name,
		Bio:                  p.Bio,
		Status:               userStatusFromProto(p.Status),
		CreatedAt:            p.CreatedAt.AsTime(),
		Score:                FromInt64Ptr(p.Score),
		ExternalID:           uuid.MustParse(p.ExternalId),
		UpdatedAt:            TimestampProtoToTime(p.UpdatedAt),
		Settings:             ProtoStructToMap(p.Settings),
		Labels:               ProtoStructToMap(p.Labels),
		TagNames:             p.TagNames,
		Metadata:             UserMetadataFromProto(p.Metadata),
		PostIDs:              FromInt64Slice(p.PostIds),
		Posts:                PostListFromProto(p.Posts),
		PinnedPostID:         int(p.PinnedPostId),
		PinnedPost:           PostFromProto(p.PinnedPost),
		TagIDs:               FromInt64Slice(p.TagIds),
		Tags:                 TagListFromProto(p.Tags),
		FullName:             p.FullName,
		IsPremium:            p.IsPremium,
		ExpiresAt:            p.ExpiresAt.AsTime(),
		SubscriptionDuration: p.SubscriptionDuration.AsDuration(),
	}
}

// UserListToProto converts domain.UserList to []*entpb.User.
func UserListToProto(ds domain.UserList) []*entpb.User {
	result := make([]*entpb.User, len(ds))
	for i, d := range ds {
		result[i] = UserToProto(d)
	}
	return result
}

// UserListFromProto converts []*entpb.User to domain.UserList.
func UserListFromProto(ps []*entpb.User) domain.UserList {
	result := make(domain.UserList, len(ps))
	for i, p := range ps {
		result[i] = UserFromProto(p)
	}
	return result
}
