// Code generated by entdomain, DO NOT EDIT.

package domain

type User struct {
	ID   int
	Name string
	Age  *int
}

// UserList is a slice of User.
type UserList []*User

// ToList wraps the User in a UserList.
func (e *User) ToList() UserList {
	return UserList{e}
}

// GetIDs returns the ID of each item in the list.
func (ds UserList) GetIDs() []int {
	ids := make([]int, len(ds))
	for i, d := range ds {
		ids[i] = d.ID
	}
	return ids
}
