// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// PostsColumns holds the columns for the "posts" table.
	PostsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "title", Type: field.TypeString},
		{Name: "published", Type: field.TypeBool, Default: false},
		{Name: "user_posts", Type: field.TypeInt, Nullable: true},
	}
	// PostsTable holds the schema information for the "posts" table.
	PostsTable = &schema.Table{
		Name:       "posts",
		Columns:    PostsColumns,
		PrimaryKey: []*schema.Column{PostsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "posts_users_posts",
				Columns:    []*schema.Column{PostsColumns[3]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// TagsColumns holds the columns for the "tags" table.
	TagsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
	}
	// TagsTable holds the schema information for the "tags" table.
	TagsTable = &schema.Table{
		Name:       "tags",
		Columns:    TagsColumns,
		PrimaryKey: []*schema.Column{TagsColumns[0]},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "bio", Type: field.TypeString, Nullable: true},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"active", "inactive"}, Default: "active"},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "username", Type: field.TypeString},
		{Name: "score", Type: field.TypeInt, Nullable: true},
		{Name: "external_id", Type: field.TypeUUID},
		{Name: "updated_at", Type: field.TypeTime, Nullable: true},
		{Name: "settings", Type: field.TypeJSON, Nullable: true},
		{Name: "labels", Type: field.TypeJSON},
		{Name: "tag_names", Type: field.TypeJSON},
		{Name: "metadata", Type: field.TypeJSON},
		{Name: "user_pinned_post", Type: field.TypeInt, Nullable: true},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "users_posts_pinned_post",
				Columns:    []*schema.Column{UsersColumns[13]},
				RefColumns: []*schema.Column{PostsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// UserTagsColumns holds the columns for the "user_tags" table.
	UserTagsColumns = []*schema.Column{
		{Name: "user_id", Type: field.TypeInt},
		{Name: "tag_id", Type: field.TypeInt},
	}
	// UserTagsTable holds the schema information for the "user_tags" table.
	UserTagsTable = &schema.Table{
		Name:       "user_tags",
		Columns:    UserTagsColumns,
		PrimaryKey: []*schema.Column{UserTagsColumns[0], UserTagsColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "user_tags_user_id",
				Columns:    []*schema.Column{UserTagsColumns[0]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "user_tags_tag_id",
				Columns:    []*schema.Column{UserTagsColumns[1]},
				RefColumns: []*schema.Column{TagsColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		PostsTable,
		TagsTable,
		UsersTable,
		UserTagsTable,
	}
)

func init() {
	PostsTable.ForeignKeys[0].RefTable = UsersTable
	UsersTable.ForeignKeys[0].RefTable = PostsTable
	UserTagsTable.ForeignKeys[0].RefTable = UsersTable
	UserTagsTable.ForeignKeys[1].RefTable = TagsTable
}
