// Code generated by ent, DO NOT EDIT.

package ent

import (
	"github.com/danhtran94/entdomain"
	domain "github.com/danhtran94/entdomain/internal/testdata/domain"
	"github.com/danhtran94/entdomain/internal/testdata/ent/user"
)

// PostDomainField is the type for Post domain field constants.
type PostDomainField = string

const (
	PostDomainFieldTitle     PostDomainField = "title"
	PostDomainFieldPublished PostDomainField = "published"
)

// PostDomainTransformer holds optional transformer functions for Post → domain mapping.
type PostDomainTransformer struct {
}

// PostTransformer is the package-level transformer for Post (nil by default).
var PostTransformer *PostDomainTransformer

// ToDomain maps the ent Post to a domain.Post.
func (e *Post) ToDomain() *domain.Post {
	d := &domain.Post{
		ID:        e.ID,
		Title:     e.Title,
		Published: e.Published,
	}
	return d
}

// ApplyDomain applies domain.Post fields to the PostCreate builder.
func (c *PostCreate) ApplyDomain(d *domain.Post, opts ...entdomain.ApplyOption) *PostCreate {
	cfg := entdomain.NewApplyConfig(opts...)
	if cfg.ShouldApply("title", d.Title) {
		c = c.SetTitle(d.Title)
	}
	if cfg.ShouldApply("published", d.Published) {
		c = c.SetPublished(d.Published)
	}
	return c
}

// ApplyDomain applies domain.Post fields to the PostUpdateOne builder.
func (u *PostUpdateOne) ApplyDomain(d *domain.Post, opts ...entdomain.ApplyOption) *PostUpdateOne {
	cfg := entdomain.NewApplyConfig(opts...)
	if cfg.ShouldApply("title", d.Title) {
		u = u.SetTitle(d.Title)
	}
	if cfg.ShouldApply("published", d.Published) {
		u = u.SetPublished(d.Published)
	}
	return u
}

// UserDomainField is the type for User domain field constants.
type UserDomainField = string

const (
	UserDomainFieldName      UserDomainField = "name"
	UserDomainFieldBio       UserDomainField = "bio"
	UserDomainFieldStatus    UserDomainField = "status"
	UserDomainFieldCreatedAt UserDomainField = "created_at"
	UserDomainFieldUsername  UserDomainField = "username"
	UserDomainFieldScore     UserDomainField = "score"
	UserDomainFieldPostIDs   UserDomainField = "post_ids"
)

// UserDomainTransformer holds optional transformer functions for User → domain mapping.
type UserDomainTransformer struct {
	GetFullName          func(e *User) string
	SetFullNameOnCreate  func(c *UserCreate, val string)
	SetFullNameOnUpdate  func(u *UserUpdateOne, val string)
	GetIsPremium         func(e *User) bool
	SetIsPremiumOnCreate func(c *UserCreate, val bool)
	SetIsPremiumOnUpdate func(u *UserUpdateOne, val bool)
	GetMetadata          func(e *User) map[string]any
	SetMetadataOnCreate  func(c *UserCreate, val map[string]any)
	SetMetadataOnUpdate  func(u *UserUpdateOne, val map[string]any)
}

// UserTransformer is the package-level transformer for User (nil by default).
var UserTransformer *UserDomainTransformer

// ToDomain maps the ent User to a domain.User.
func (e *User) ToDomain() *domain.User {
	d := &domain.User{
		ID:        e.ID,
		Name:      e.Name,
		Bio:       &e.Bio,
		Status:    domain.UserStatus(e.Status),
		CreatedAt: e.CreatedAt,
		Username:  e.Username,
		Score:     &e.Score,
	}
	for _, _e := range e.Edges.Posts {
		d.PostIDs = append(d.PostIDs, _e.ID)
		d.Posts = append(d.Posts, *_e.ToDomain())
	}
	if UserTransformer != nil && UserTransformer.GetFullName != nil {
		d.FullName = UserTransformer.GetFullName(e)
	}
	if UserTransformer != nil && UserTransformer.GetIsPremium != nil {
		d.IsPremium = UserTransformer.GetIsPremium(e)
	}
	if UserTransformer != nil && UserTransformer.GetMetadata != nil {
		d.Metadata = UserTransformer.GetMetadata(e)
	}
	return d
}

// ApplyDomain applies domain.User fields to the UserCreate builder.
func (c *UserCreate) ApplyDomain(d *domain.User, opts ...entdomain.ApplyOption) *UserCreate {
	cfg := entdomain.NewApplyConfig(opts...)
	if cfg.ShouldApply("name", d.Name) {
		c = c.SetName(d.Name)
	}
	if cfg.ShouldApplyPtr("bio", d.Bio) {
		c = c.SetNillableBio(d.Bio)
	}
	if cfg.ShouldApply("status", d.Status) {
		c = c.SetStatus(user.Status(d.Status))
	}
	if cfg.ShouldApply("created_at", d.CreatedAt) {
		c = c.SetCreatedAt(d.CreatedAt)
	}
	if cfg.ShouldApply("username", d.Username) {
		c = c.SetUsername(d.Username)
	}
	if cfg.ShouldApplyPtr("score", d.Score) {
		c = c.SetNillableScore(d.Score)
	}
	if len(d.PostIDs) > 0 {
		c = c.AddPostIDs(d.PostIDs...)
	}
	if UserTransformer != nil && UserTransformer.SetFullNameOnCreate != nil {
		UserTransformer.SetFullNameOnCreate(c, d.FullName)
	}
	if UserTransformer != nil && UserTransformer.SetIsPremiumOnCreate != nil {
		UserTransformer.SetIsPremiumOnCreate(c, d.IsPremium)
	}
	if UserTransformer != nil && UserTransformer.SetMetadataOnCreate != nil {
		UserTransformer.SetMetadataOnCreate(c, d.Metadata)
	}
	return c
}

// ApplyDomain applies domain.User fields to the UserUpdateOne builder.
func (u *UserUpdateOne) ApplyDomain(d *domain.User, opts ...entdomain.ApplyOption) *UserUpdateOne {
	cfg := entdomain.NewApplyConfig(opts...)
	if cfg.ShouldApply("name", d.Name) {
		u = u.SetName(d.Name)
	}
	if cfg.ShouldApplyPtr("bio", d.Bio) {
		u = u.SetNillableBio(d.Bio)
	}
	if cfg.ShouldApply("status", d.Status) {
		u = u.SetStatus(user.Status(d.Status))
	}
	if cfg.ShouldApplyPtr("score", d.Score) {
		u = u.SetNillableScore(d.Score)
	}
	if cfg.IsAppendEdge("post_ids") {
		u = u.AddPostIDs(d.PostIDs...)
	} else {
		u = u.ClearPosts().AddPostIDs(d.PostIDs...)
	}
	if UserTransformer != nil && UserTransformer.SetFullNameOnUpdate != nil {
		UserTransformer.SetFullNameOnUpdate(u, d.FullName)
	}
	if UserTransformer != nil && UserTransformer.SetIsPremiumOnUpdate != nil {
		UserTransformer.SetIsPremiumOnUpdate(u, d.IsPremium)
	}
	if UserTransformer != nil && UserTransformer.SetMetadataOnUpdate != nil {
		UserTransformer.SetMetadataOnUpdate(u, d.Metadata)
	}
	return u
}
