// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/danhtran94/entdomain/internal/testdata/ent/post"
	"github.com/danhtran94/entdomain/internal/testdata/ent/schema"
	"github.com/danhtran94/entdomain/internal/testdata/ent/user"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	postFields := schema.Post{}.Fields()
	_ = postFields
	// postDescPublished is the schema descriptor for published field.
	postDescPublished := postFields[1].Descriptor()
	// post.DefaultPublished holds the default value on creation for the published field.
	post.DefaultPublished = postDescPublished.Default.(bool)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[3].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
}
