// Code generated by entdomain, DO NOT EDIT.

package domain

type Post struct {
	ID        int
	Title     string
	Published bool
	OwnerID   int
	PinnerIDs []int
}

// PostList is a slice of Post.
type PostList []*Post

// ToList wraps the Post in a PostList.
func (e *Post) ToList() PostList {
	return PostList{e}
}

// GetIDs returns the ID of each item in the list.
// Nil elements yield the zero value of the ID type at their index.
func (ds PostList) GetIDs() []int {
	ids := make([]int, len(ds))
	for i, d := range ds {
		if d == nil {
			continue
		}
		ids[i] = d.ID
	}
	return ids
}
