// Code generated by entdomain, DO NOT EDIT.

package domain

type Tag struct {
	ID      int
	Name    string
	UserIDs []int
	Users   UserList
}

// TagList is a slice of Tag.
type TagList []*Tag

// ToList wraps the Tag in a TagList.
func (e *Tag) ToList() TagList {
	return TagList{e}
}

// GetIDs returns the ID of each item in the list.
// Nil elements yield the zero value of the ID type at their index.
func (ds TagList) GetIDs() []int {
	ids := make([]int, len(ds))
	for i, d := range ds {
		if d == nil {
			continue
		}
		ids[i] = d.ID
	}
	return ids
}
