// Code generated by entdomain, DO NOT EDIT.

package domain

import (
	"time"
)

type UserStatus string

const (
	UserStatusActive   UserStatus = "active"
	UserStatusInactive UserStatus = "inactive"
)

type User struct {
	ID         int
	Name       string
	Bio        *string
	Status     UserStatus
	CreatedAt  time.Time
	Username   string
	Score      *int
	PostIDs    []int
	Posts      PostList
	PinnedPost Post
	FullName   string
	IsPremium  bool
	Metadata   map[string]any
}

// UserList is a slice of User.
type UserList []*User

// ToList wraps the User in a UserList.
func (e *User) ToList() UserList {
	return UserList{e}
}

// GetIDs returns the ID of each item in the list.
func (ds UserList) GetIDs() []int {
	ids := make([]int, len(ds))
	for i, d := range ds {
		ids[i] = d.ID
	}
	return ids
}
