// Code generated by entdomain, DO NOT EDIT.

package domain

import (
	"github.com/google/uuid"
	"time"
)

type UserStatus string

const (
	UserStatusActive   UserStatus = "active"
	UserStatusInactive UserStatus = "inactive"
)

type User struct {
	ID                   int
	Name                 string
	Bio                  *string
	Status               UserStatus
	CreatedAt            time.Time
	Username             string
	Score                *int
	ExternalID           uuid.UUID
	UpdatedAt            *time.Time
	Settings             map[string]interface{}
	Labels               map[string]interface{}
	TagNames             []string
	Metadata             UserMetadata
	PostIDs              []int
	Posts                PostList
	PinnedPostID         int
	PinnedPost           *Post
	TagIDs               []int
	Tags                 TagList
	FullName             string
	IsPremium            bool
	ExpiresAt            time.Time
	SubscriptionDuration time.Duration
}

// UserList is a slice of User.
type UserList []*User

// ToList wraps the User in a UserList.
func (e *User) ToList() UserList {
	return UserList{e}
}

// GetIDs returns the ID of each item in the list.
func (ds UserList) GetIDs() []int {
	ids := make([]int, len(ds))
	for i, d := range ds {
		ids[i] = d.ID
	}
	return ids
}
