// Code generated by entdomain, DO NOT EDIT.

package domain

import (
	"time"
)

type UserStatus string

const (
	UserStatusActive   UserStatus = "active"
	UserStatusInactive UserStatus = "inactive"
)

type User struct {
	ID        int
	Name      string
	Bio       *string
	Status    UserStatus
	CreatedAt time.Time
	Username  string
	Score     *int
	PostIDs   []int
	Posts     []Post
	FullName  string
	IsPremium bool
	Metadata  map[string]any
}
