// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"github.com/danhtran94/entdomain"
	domain "github.com/danhtran94/entdomain/examples/custom/internal/domain"
)

// UserDomainField is the type for User domain field constants.
type UserDomainField = string

const (
	UserDomainFieldName UserDomainField = "name"
	UserDomainFieldAge  UserDomainField = "age"
)

// UserDomainTransformer holds optional transformer functions for User → domain mapping.
//
// Get* functions are pure synchronous projections invoked by ToDomain.
// Set*OnCreate / Set*OnUpdate are invoked during ApplyDomain and may perform
// I/O (e.g. KMS-backed field encryption); they receive ctx + the full domain
// struct so they can access sibling fields and propagate cancellation.
type UserDomainTransformer struct {
}

// UserTransformer is the package-level transformer for User (nil by default).
var UserTransformer *UserDomainTransformer

// ToDomain maps the ent User to a domain.User.
func (e *User) ToDomain() *domain.User {
	d := &domain.User{
		ID:   e.ID,
		Name: e.Name,
		Age:  &e.Age,
	}
	return d
}

// ApplyDomain applies domain.User fields to the UserCreate builder.
func (c *UserCreate) ApplyDomain(ctx context.Context, d *domain.User, opts ...entdomain.ApplyOption) (*UserCreate, error) {
	cfg := entdomain.NewApplyConfig(opts...)
	_ = cfg
	_ = ctx
	if cfg.ShouldApply("name", d.Name) {
		c = c.SetName(d.Name)
	}
	if cfg.ShouldApplyPtr("age", d.Age) && d.Age != nil {
		c = c.SetAge(*d.Age)
	}
	return c, nil
}

// ApplyDomainX is the panicking variant of ApplyDomain. It enables fluent
// chaining at the cost of converting transformer errors into panics. Mirrors
// ent's SaveX/FirstX/OnlyX convention: use in tests and scripts, prefer
// ApplyDomain on request paths where transformer errors (e.g. KMS failures)
// must be recoverable.
func (c *UserCreate) ApplyDomainX(ctx context.Context, d *domain.User, opts ...entdomain.ApplyOption) *UserCreate {
	b, err := c.ApplyDomain(ctx, d, opts...)
	if err != nil {
		panic(err)
	}
	return b
}

// ApplyDomain applies domain.User fields to the UserUpdateOne builder.
func (u *UserUpdateOne) ApplyDomain(ctx context.Context, d *domain.User, opts ...entdomain.ApplyOption) (*UserUpdateOne, error) {
	cfg := entdomain.NewApplyConfig(opts...)
	_ = cfg
	_ = ctx
	if cfg.ShouldApply("name", d.Name) {
		u = u.SetName(d.Name)
	}
	if cfg.ShouldApplyPtr("age", d.Age) && d.Age != nil {
		u = u.SetAge(*d.Age)
	}
	return u, nil
}

// ApplyDomainX is the panicking variant of ApplyDomain. See *UserCreate.ApplyDomainX.
func (u *UserUpdateOne) ApplyDomainX(ctx context.Context, d *domain.User, opts ...entdomain.ApplyOption) *UserUpdateOne {
	b, err := u.ApplyDomain(ctx, d, opts...)
	if err != nil {
		panic(err)
	}
	return b
}

// ApplyDomain applies domain.User fields to the UserUpdate builder.
// Chain .Where(...) conditions to target specific records.
//
// Note: ctx is accepted for API symmetry with ApplyDomainCreate/UpdateOne and
// to allow future ctx-aware field transformers. Currently no transformer hooks
// fire here — the error return is always nil.
func (u *UserUpdate) ApplyDomain(ctx context.Context, d *domain.User, opts ...entdomain.ApplyOption) (*UserUpdate, error) {
	cfg := entdomain.NewApplyConfig(opts...)
	_ = cfg
	_ = ctx
	if cfg.ShouldApply("name", d.Name) {
		u = u.SetName(d.Name)
	}
	if cfg.ShouldApplyPtr("age", d.Age) && d.Age != nil {
		u = u.SetAge(*d.Age)
	}
	return u, nil
}

// ApplyDomainX is the panicking variant of ApplyDomain. See *UserCreate.ApplyDomainX.
func (u *UserUpdate) ApplyDomainX(ctx context.Context, d *domain.User, opts ...entdomain.ApplyOption) *UserUpdate {
	b, err := u.ApplyDomain(ctx, d, opts...)
	if err != nil {
		panic(err)
	}
	return b
}

// ApplyDomain applies domain.User fields to the UserUpsertOne builder on conflict.
//
// Note: ctx is accepted for API symmetry. Transformer hooks do not fire on
// upsert conflict paths; the error return is always nil.
func (u *UserUpsertOne) ApplyDomain(ctx context.Context, d *domain.User, opts ...entdomain.ApplyOption) (*UserUpsertOne, error) {
	cfg := entdomain.NewApplyConfig(opts...)
	_ = cfg
	_ = ctx
	u = u.Update(func(uu *UserUpsert) {
		if cfg.ShouldApply("name", d.Name) {
			uu.SetName(d.Name)
		}
		if cfg.ShouldApplyPtr("age", d.Age) && d.Age != nil {
			uu.SetAge(*d.Age)
		}
	})
	return u, nil
}

// ApplyDomainX is the panicking variant of ApplyDomain. See *UserCreate.ApplyDomainX.
func (u *UserUpsertOne) ApplyDomainX(ctx context.Context, d *domain.User, opts ...entdomain.ApplyOption) *UserUpsertOne {
	b, err := u.ApplyDomain(ctx, d, opts...)
	if err != nil {
		panic(err)
	}
	return b
}

// ApplyDomain applies domain.User fields to the UserUpsertBulk builder on conflict.
//
// Note: ctx is accepted for API symmetry. Transformer hooks do not fire on
// upsert conflict paths; the error return is always nil.
func (u *UserUpsertBulk) ApplyDomain(ctx context.Context, d *domain.User, opts ...entdomain.ApplyOption) (*UserUpsertBulk, error) {
	cfg := entdomain.NewApplyConfig(opts...)
	_ = cfg
	_ = ctx
	u = u.Update(func(uu *UserUpsert) {
		if cfg.ShouldApply("name", d.Name) {
			uu.SetName(d.Name)
		}
		if cfg.ShouldApplyPtr("age", d.Age) && d.Age != nil {
			uu.SetAge(*d.Age)
		}
	})
	return u, nil
}

// ApplyDomainX is the panicking variant of ApplyDomain. See *UserCreate.ApplyDomainX.
func (u *UserUpsertBulk) ApplyDomainX(ctx context.Context, d *domain.User, opts ...entdomain.ApplyOption) *UserUpsertBulk {
	b, err := u.ApplyDomain(ctx, d, opts...)
	if err != nil {
		panic(err)
	}
	return b
}

// ToDomain maps a slice of ent User to domain.UserList.
func (es Users) ToDomain() domain.UserList {
	ds := make(domain.UserList, len(es))
	for i, e := range es {
		ds[i] = e.ToDomain()
	}
	return ds
}

// CreateBulkDomain creates a UserCreateBulk from domain.UserList.
//
// If any per-row transformer returns an error, the first such error is
// returned immediately and partial bulk is discarded.
func (c *UserClient) CreateBulkDomain(ctx context.Context, ds domain.UserList, opts ...entdomain.ApplyOption) (*UserCreateBulk, error) {
	builders := make([]*UserCreate, len(ds))
	for i := range ds {
		b, err := c.Create().ApplyDomain(ctx, ds[i], opts...)
		if err != nil {
			return nil, err
		}
		builders[i] = b
	}
	return c.CreateBulk(builders...), nil
}

// CreateBulkDomainX is the panicking variant of CreateBulkDomain. See
// *UserCreate.ApplyDomainX for the convention.
func (c *UserClient) CreateBulkDomainX(ctx context.Context, ds domain.UserList, opts ...entdomain.ApplyOption) *UserCreateBulk {
	b, err := c.CreateBulkDomain(ctx, ds, opts...)
	if err != nil {
		panic(err)
	}
	return b
}

// UserUpdateOneBulk holds a set of UserUpdateOne builders.
type UserUpdateOneBulk struct {
	builders []*UserUpdateOne
}

// Save executes all builders and returns the updated entities as domain.UserList.
func (b *UserUpdateOneBulk) Save(ctx context.Context) (domain.UserList, error) {
	result := make(domain.UserList, 0, len(b.builders))
	for _, builder := range b.builders {
		updated, err := builder.Save(ctx)
		if err != nil {
			return nil, err
		}
		result = append(result, updated.ToDomain())
	}
	return result, nil
}

// SaveX is like Save but panics on error.
func (b *UserUpdateOneBulk) SaveX(ctx context.Context) domain.UserList {
	result, err := b.Save(ctx)
	if err != nil {
		panic(err)
	}
	return result
}

// Exec executes all builders without returning the updated entities.
func (b *UserUpdateOneBulk) Exec(ctx context.Context) error {
	_, err := b.Save(ctx)
	return err
}

// ExecX is like Exec but panics on error.
func (b *UserUpdateOneBulk) ExecX(ctx context.Context) {
	if err := b.Exec(ctx); err != nil {
		panic(err)
	}
}

// UpdateBulkDomain returns a UserUpdateOneBulk from domain.UserList.
// Each builder is keyed on ds[i].ID.
//
// If any per-row transformer returns an error, the first such error is
// returned immediately and partial bulk is discarded.
func (c *UserClient) UpdateBulkDomain(ctx context.Context, ds domain.UserList, opts ...entdomain.ApplyOption) (*UserUpdateOneBulk, error) {
	builders := make([]*UserUpdateOne, len(ds))
	for i := range ds {
		b, err := c.UpdateOneID(ds[i].ID).ApplyDomain(ctx, ds[i], opts...)
		if err != nil {
			return nil, err
		}
		builders[i] = b
	}
	return &UserUpdateOneBulk{builders: builders}, nil
}

// UpdateBulkDomainX is the panicking variant of UpdateBulkDomain. See
// *UserCreate.ApplyDomainX for the convention.
func (c *UserClient) UpdateBulkDomainX(ctx context.Context, ds domain.UserList, opts ...entdomain.ApplyOption) *UserUpdateOneBulk {
	b, err := c.UpdateBulkDomain(ctx, ds, opts...)
	if err != nil {
		panic(err)
	}
	return b
}
