// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"github.com/danhtran94/entdomain"
	domain "github.com/danhtran94/entdomain/examples/custom/internal/domain"
)

// UserDomainField is the type for User domain field constants.
type UserDomainField = string

const (
	UserDomainFieldName UserDomainField = "name"
	UserDomainFieldAge  UserDomainField = "age"
)

// UserDomainTransformer holds optional transformer functions for User → domain mapping.
type UserDomainTransformer struct {
}

// UserTransformer is the package-level transformer for User (nil by default).
var UserTransformer *UserDomainTransformer

// ToDomain maps the ent User to a domain.User.
func (e *User) ToDomain() *domain.User {
	d := &domain.User{
		ID:   e.ID,
		Name: e.Name,
		Age:  &e.Age,
	}
	return d
}

// ApplyDomain applies domain.User fields to the UserCreate builder.
func (c *UserCreate) ApplyDomain(d *domain.User, opts ...entdomain.ApplyOption) *UserCreate {
	cfg := entdomain.NewApplyConfig(opts...)
	if cfg.ShouldApply("name", d.Name) {
		c = c.SetName(d.Name)
	}
	if cfg.ShouldApplyPtr("age", d.Age) {
		c = c.SetNillableAge(d.Age)
	}
	return c
}

// ApplyDomain applies domain.User fields to the UserUpdateOne builder.
func (u *UserUpdateOne) ApplyDomain(d *domain.User, opts ...entdomain.ApplyOption) *UserUpdateOne {
	cfg := entdomain.NewApplyConfig(opts...)
	if cfg.ShouldApply("name", d.Name) {
		u = u.SetName(d.Name)
	}
	if cfg.ShouldApplyPtr("age", d.Age) {
		u = u.SetNillableAge(d.Age)
	}
	return u
}

// ApplyDomain applies domain.User fields to the UserUpdate builder.
// Chain .Where(...) conditions to target specific records.
func (u *UserUpdate) ApplyDomain(d *domain.User, opts ...entdomain.ApplyOption) *UserUpdate {
	cfg := entdomain.NewApplyConfig(opts...)
	if cfg.ShouldApply("name", d.Name) {
		u = u.SetName(d.Name)
	}
	if cfg.ShouldApplyPtr("age", d.Age) {
		u = u.SetNillableAge(d.Age)
	}
	return u
}

// ApplyDomain applies domain.User fields to the UserUpsertOne builder on conflict.
func (u *UserUpsertOne) ApplyDomain(d *domain.User, opts ...entdomain.ApplyOption) *UserUpsertOne {
	cfg := entdomain.NewApplyConfig(opts...)
	_ = cfg
	return u.Update(func(uu *UserUpsert) {
		if cfg.ShouldApply("name", d.Name) {
			uu.SetName(d.Name)
		}
		if cfg.ShouldApplyPtr("age", d.Age) && d.Age != nil {
			uu.SetAge(*d.Age)
		}
	})
}

// ApplyDomain applies domain.User fields to the UserUpsertBulk builder on conflict.
func (u *UserUpsertBulk) ApplyDomain(d *domain.User, opts ...entdomain.ApplyOption) *UserUpsertBulk {
	cfg := entdomain.NewApplyConfig(opts...)
	_ = cfg
	return u.Update(func(uu *UserUpsert) {
		if cfg.ShouldApply("name", d.Name) {
			uu.SetName(d.Name)
		}
		if cfg.ShouldApplyPtr("age", d.Age) && d.Age != nil {
			uu.SetAge(*d.Age)
		}
	})
}

// ToDomain maps a slice of ent User to domain.UserList.
func (es Users) ToDomain() domain.UserList {
	ds := make(domain.UserList, len(es))
	for i, e := range es {
		ds[i] = e.ToDomain()
	}
	return ds
}

// CreateBulkDomain creates a UserCreateBulk from domain.UserList.
func (c *UserClient) CreateBulkDomain(ds domain.UserList, opts ...entdomain.ApplyOption) *UserCreateBulk {
	builders := make([]*UserCreate, len(ds))
	for i := range ds {
		builders[i] = c.Create().ApplyDomain(ds[i], opts...)
	}
	return c.CreateBulk(builders...)
}

// UserUpdateOneBulk holds a set of UserUpdateOne builders.
type UserUpdateOneBulk struct {
	builders []*UserUpdateOne
}

// Save executes all builders and returns the updated entities as domain.UserList.
func (b *UserUpdateOneBulk) Save(ctx context.Context) (domain.UserList, error) {
	result := make(domain.UserList, 0, len(b.builders))
	for _, builder := range b.builders {
		updated, err := builder.Save(ctx)
		if err != nil {
			return nil, err
		}
		result = append(result, updated.ToDomain())
	}
	return result, nil
}

// SaveX is like Save but panics on error.
func (b *UserUpdateOneBulk) SaveX(ctx context.Context) domain.UserList {
	result, err := b.Save(ctx)
	if err != nil {
		panic(err)
	}
	return result
}

// Exec executes all builders without returning the updated entities.
func (b *UserUpdateOneBulk) Exec(ctx context.Context) error {
	_, err := b.Save(ctx)
	return err
}

// ExecX is like Exec but panics on error.
func (b *UserUpdateOneBulk) ExecX(ctx context.Context) {
	if err := b.Exec(ctx); err != nil {
		panic(err)
	}
}

// UpdateBulkDomain returns a UserUpdateOneBulk from domain.UserList.
// Each builder is keyed on ds[i].ID.
func (c *UserClient) UpdateBulkDomain(ds domain.UserList, opts ...entdomain.ApplyOption) *UserUpdateOneBulk {
	builders := make([]*UserUpdateOne, len(ds))
	for i := range ds {
		builders[i] = c.UpdateOneID(ds[i].ID).ApplyDomain(ds[i], opts...)
	}
	return &UserUpdateOneBulk{builders: builders}
}
