// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"time"

	"github.com/danhtran94/entdomain"
	domain "github.com/danhtran94/entdomain/examples/basic/domain"
	"github.com/danhtran94/entdomain/examples/basic/ent/user"
)

// PostDomainField is the type for Post domain field constants.
type PostDomainField = string

const (
	PostDomainFieldTitle     PostDomainField = "title"
	PostDomainFieldPublished PostDomainField = "published"
	PostDomainFieldOwnerID   PostDomainField = "owner_id"
	PostDomainFieldPinnerIDs PostDomainField = "pinner_ids"
)

// PostDomainTransformer holds optional transformer functions for Post → domain mapping.
type PostDomainTransformer struct {
}

// PostTransformer is the package-level transformer for Post (nil by default).
var PostTransformer *PostDomainTransformer

// ToDomain maps the ent Post to a domain.Post.
func (e *Post) ToDomain() *domain.Post {
	d := &domain.Post{
		ID:        e.ID,
		Title:     e.Title,
		Published: e.Published,
	}
	if _e := e.Edges.Owner; _e != nil {
		d.OwnerID = _e.ID
	}
	for _, _e := range e.Edges.Pinners {
		d.PinnerIDs = append(d.PinnerIDs, _e.ID)
	}
	return d
}

// ApplyDomain applies domain.Post fields to the PostCreate builder.
func (c *PostCreate) ApplyDomain(d *domain.Post, opts ...entdomain.ApplyOption) *PostCreate {
	cfg := entdomain.NewApplyConfig(opts...)
	if cfg.ShouldApply("title", d.Title) {
		c = c.SetTitle(d.Title)
	}
	if cfg.ShouldApply("published", d.Published) {
		c = c.SetPublished(d.Published)
	}
	if len(d.PinnerIDs) > 0 {
		c = c.AddPinnerIDs(d.PinnerIDs...)
	}
	return c
}

// ApplyDomain applies domain.Post fields to the PostUpdateOne builder.
func (u *PostUpdateOne) ApplyDomain(d *domain.Post, opts ...entdomain.ApplyOption) *PostUpdateOne {
	cfg := entdomain.NewApplyConfig(opts...)
	_ = cfg
	if cfg.ShouldApply("title", d.Title) {
		u = u.SetTitle(d.Title)
	}
	if cfg.ShouldApply("published", d.Published) {
		u = u.SetPublished(d.Published)
	}
	if cfg.IsAppendEdge("pinner_ids") {
		u = u.AddPinnerIDs(d.PinnerIDs...)
	} else {
		u = u.ClearPinners().AddPinnerIDs(d.PinnerIDs...)
	}
	return u
}

// ApplyDomain applies domain.Post fields to the PostUpdate builder.
// Chain .Where(...) conditions to target specific records.
func (u *PostUpdate) ApplyDomain(d *domain.Post, opts ...entdomain.ApplyOption) *PostUpdate {
	cfg := entdomain.NewApplyConfig(opts...)
	_ = cfg
	if cfg.ShouldApply("title", d.Title) {
		u = u.SetTitle(d.Title)
	}
	if cfg.ShouldApply("published", d.Published) {
		u = u.SetPublished(d.Published)
	}
	if cfg.IsAppendEdge("pinner_ids") {
		u = u.AddPinnerIDs(d.PinnerIDs...)
	} else {
		u = u.ClearPinners().AddPinnerIDs(d.PinnerIDs...)
	}
	return u
}

// ApplyDomain applies domain.Post fields to the PostUpsertOne builder on conflict.
func (u *PostUpsertOne) ApplyDomain(d *domain.Post, opts ...entdomain.ApplyOption) *PostUpsertOne {
	cfg := entdomain.NewApplyConfig(opts...)
	_ = cfg
	return u.Update(func(uu *PostUpsert) {
		if cfg.ShouldApply("title", d.Title) {
			uu.SetTitle(d.Title)
		}
		if cfg.ShouldApply("published", d.Published) {
			uu.SetPublished(d.Published)
		}
	})
}

// ToDomain maps a slice of ent Post to domain.PostList.
func (es Posts) ToDomain() domain.PostList {
	ds := make(domain.PostList, len(es))
	for i, e := range es {
		ds[i] = e.ToDomain()
	}
	return ds
}

// TagDomainField is the type for Tag domain field constants.
type TagDomainField = string

const (
	TagDomainFieldName    TagDomainField = "name"
	TagDomainFieldUserIDs TagDomainField = "user_ids"
)

// TagDomainTransformer holds optional transformer functions for Tag → domain mapping.
type TagDomainTransformer struct {
}

// TagTransformer is the package-level transformer for Tag (nil by default).
var TagTransformer *TagDomainTransformer

// ToDomain maps the ent Tag to a domain.Tag.
func (e *Tag) ToDomain() *domain.Tag {
	d := &domain.Tag{
		ID:   e.ID,
		Name: e.Name,
	}
	for _, _e := range e.Edges.Users {
		d.UserIDs = append(d.UserIDs, _e.ID)
		d.Users = append(d.Users, _e.ToDomain())
	}
	return d
}

// ApplyDomain applies domain.Tag fields to the TagCreate builder.
func (c *TagCreate) ApplyDomain(d *domain.Tag, opts ...entdomain.ApplyOption) *TagCreate {
	cfg := entdomain.NewApplyConfig(opts...)
	if cfg.ShouldApply("name", d.Name) {
		c = c.SetName(d.Name)
	}
	if len(d.UserIDs) > 0 {
		c = c.AddUserIDs(d.UserIDs...)
	}
	return c
}

// ApplyDomain applies domain.Tag fields to the TagUpdateOne builder.
func (u *TagUpdateOne) ApplyDomain(d *domain.Tag, opts ...entdomain.ApplyOption) *TagUpdateOne {
	cfg := entdomain.NewApplyConfig(opts...)
	_ = cfg
	if cfg.ShouldApply("name", d.Name) {
		u = u.SetName(d.Name)
	}
	if cfg.IsAppendEdge("user_ids") {
		u = u.AddUserIDs(d.UserIDs...)
	} else {
		u = u.ClearUsers().AddUserIDs(d.UserIDs...)
	}
	return u
}

// ApplyDomain applies domain.Tag fields to the TagUpdate builder.
// Chain .Where(...) conditions to target specific records.
func (u *TagUpdate) ApplyDomain(d *domain.Tag, opts ...entdomain.ApplyOption) *TagUpdate {
	cfg := entdomain.NewApplyConfig(opts...)
	_ = cfg
	if cfg.ShouldApply("name", d.Name) {
		u = u.SetName(d.Name)
	}
	if cfg.IsAppendEdge("user_ids") {
		u = u.AddUserIDs(d.UserIDs...)
	} else {
		u = u.ClearUsers().AddUserIDs(d.UserIDs...)
	}
	return u
}

// ApplyDomain applies domain.Tag fields to the TagUpsertOne builder on conflict.
func (u *TagUpsertOne) ApplyDomain(d *domain.Tag, opts ...entdomain.ApplyOption) *TagUpsertOne {
	cfg := entdomain.NewApplyConfig(opts...)
	_ = cfg
	return u.Update(func(uu *TagUpsert) {
		if cfg.ShouldApply("name", d.Name) {
			uu.SetName(d.Name)
		}
	})
}

// ApplyDomain applies domain.Tag fields to the TagUpsertBulk builder on conflict.
func (u *TagUpsertBulk) ApplyDomain(d *domain.Tag, opts ...entdomain.ApplyOption) *TagUpsertBulk {
	cfg := entdomain.NewApplyConfig(opts...)
	_ = cfg
	return u.Update(func(uu *TagUpsert) {
		if cfg.ShouldApply("name", d.Name) {
			uu.SetName(d.Name)
		}
	})
}

// ToDomain maps a slice of ent Tag to domain.TagList.
func (es Tags) ToDomain() domain.TagList {
	ds := make(domain.TagList, len(es))
	for i, e := range es {
		ds[i] = e.ToDomain()
	}
	return ds
}

// CreateBulkDomain creates a TagCreateBulk from domain.TagList.
func (c *TagClient) CreateBulkDomain(ds domain.TagList, opts ...entdomain.ApplyOption) *TagCreateBulk {
	builders := make([]*TagCreate, len(ds))
	for i := range ds {
		builders[i] = c.Create().ApplyDomain(ds[i], opts...)
	}
	return c.CreateBulk(builders...)
}

// TagUpdateOneBulk holds a set of TagUpdateOne builders.
type TagUpdateOneBulk struct {
	builders []*TagUpdateOne
}

// Save executes all builders and returns the updated entities as domain.TagList.
func (b *TagUpdateOneBulk) Save(ctx context.Context) (domain.TagList, error) {
	result := make(domain.TagList, 0, len(b.builders))
	for _, builder := range b.builders {
		updated, err := builder.Save(ctx)
		if err != nil {
			return nil, err
		}
		result = append(result, updated.ToDomain())
	}
	return result, nil
}

// SaveX is like Save but panics on error.
func (b *TagUpdateOneBulk) SaveX(ctx context.Context) domain.TagList {
	result, err := b.Save(ctx)
	if err != nil {
		panic(err)
	}
	return result
}

// Exec executes all builders without returning the updated entities.
func (b *TagUpdateOneBulk) Exec(ctx context.Context) error {
	_, err := b.Save(ctx)
	return err
}

// ExecX is like Exec but panics on error.
func (b *TagUpdateOneBulk) ExecX(ctx context.Context) {
	if err := b.Exec(ctx); err != nil {
		panic(err)
	}
}

// UpdateBulkDomain returns a TagUpdateOneBulk from domain.TagList.
// Each builder is keyed on ds[i].ID.
func (c *TagClient) UpdateBulkDomain(ds domain.TagList, opts ...entdomain.ApplyOption) *TagUpdateOneBulk {
	builders := make([]*TagUpdateOne, len(ds))
	for i := range ds {
		builders[i] = c.UpdateOneID(ds[i].ID).ApplyDomain(ds[i], opts...)
	}
	return &TagUpdateOneBulk{builders: builders}
}

// UserDomainField is the type for User domain field constants.
type UserDomainField = string

const (
	UserDomainFieldName         UserDomainField = "name"
	UserDomainFieldBio          UserDomainField = "bio"
	UserDomainFieldStatus       UserDomainField = "status"
	UserDomainFieldCreatedAt    UserDomainField = "created_at"
	UserDomainFieldUsername     UserDomainField = "username"
	UserDomainFieldScore        UserDomainField = "score"
	UserDomainFieldExternalID   UserDomainField = "external_id"
	UserDomainFieldUpdatedAt    UserDomainField = "updated_at"
	UserDomainFieldSettings     UserDomainField = "settings"
	UserDomainFieldLabels       UserDomainField = "labels"
	UserDomainFieldTagNames     UserDomainField = "tag_names"
	UserDomainFieldMetadata     UserDomainField = "metadata"
	UserDomainFieldPostIDs      UserDomainField = "post_ids"
	UserDomainFieldPinnedPostID UserDomainField = "pinned_post_id"
	UserDomainFieldTagIDs       UserDomainField = "tag_ids"
)

// UserDomainTransformer holds optional transformer functions for User → domain mapping.
type UserDomainTransformer struct {
	GetFullName                     func(e *User) string
	SetFullNameOnCreate             func(c *UserCreate, val string)
	SetFullNameOnUpdate             func(u *UserUpdateOne, val string)
	GetIsPremium                    func(e *User) bool
	SetIsPremiumOnCreate            func(c *UserCreate, val bool)
	SetIsPremiumOnUpdate            func(u *UserUpdateOne, val bool)
	GetExpiresAt                    func(e *User) time.Time
	SetExpiresAtOnCreate            func(c *UserCreate, val time.Time)
	SetExpiresAtOnUpdate            func(u *UserUpdateOne, val time.Time)
	GetSubscriptionDuration         func(e *User) time.Duration
	SetSubscriptionDurationOnCreate func(c *UserCreate, val time.Duration)
	SetSubscriptionDurationOnUpdate func(u *UserUpdateOne, val time.Duration)
}

// UserTransformer is the package-level transformer for User (nil by default).
var UserTransformer *UserDomainTransformer

// ToDomain maps the ent User to a domain.User.
func (e *User) ToDomain() *domain.User {
	d := &domain.User{
		ID:         e.ID,
		Name:       e.Name,
		Bio:        &e.Bio,
		Status:     domain.UserStatus(e.Status),
		CreatedAt:  e.CreatedAt,
		Username:   e.Username,
		Score:      &e.Score,
		ExternalID: e.ExternalID,
		UpdatedAt:  &e.UpdatedAt,
		Settings:   e.Settings,
		Labels:     e.Labels,
		TagNames:   e.TagNames,
		Metadata:   e.Metadata,
	}
	for _, _e := range e.Edges.Posts {
		d.PostIDs = append(d.PostIDs, _e.ID)
		d.Posts = append(d.Posts, _e.ToDomain())
	}
	if _e := e.Edges.PinnedPost; _e != nil {
		d.PinnedPostID = _e.ID
		d.PinnedPost = _e.ToDomain()
	}
	for _, _e := range e.Edges.Tags {
		d.TagIDs = append(d.TagIDs, _e.ID)
		d.Tags = append(d.Tags, _e.ToDomain())
	}
	if UserTransformer != nil && UserTransformer.GetFullName != nil {
		d.FullName = UserTransformer.GetFullName(e)
	}
	if UserTransformer != nil && UserTransformer.GetIsPremium != nil {
		d.IsPremium = UserTransformer.GetIsPremium(e)
	}
	if UserTransformer != nil && UserTransformer.GetExpiresAt != nil {
		d.ExpiresAt = UserTransformer.GetExpiresAt(e)
	}
	if UserTransformer != nil && UserTransformer.GetSubscriptionDuration != nil {
		d.SubscriptionDuration = UserTransformer.GetSubscriptionDuration(e)
	}
	return d
}

// ApplyDomain applies domain.User fields to the UserCreate builder.
func (c *UserCreate) ApplyDomain(d *domain.User, opts ...entdomain.ApplyOption) *UserCreate {
	cfg := entdomain.NewApplyConfig(opts...)
	if cfg.ShouldApply("name", d.Name) {
		c = c.SetName(d.Name)
	}
	if cfg.ShouldApplyPtr("bio", d.Bio) && d.Bio != nil {
		c = c.SetBio(*d.Bio)
	}
	if cfg.ShouldApply("status", d.Status) {
		c = c.SetStatus(user.Status(d.Status))
	}
	if cfg.ShouldApply("created_at", d.CreatedAt) {
		c = c.SetCreatedAt(d.CreatedAt)
	}
	if cfg.ShouldApply("username", d.Username) {
		c = c.SetUsername(d.Username)
	}
	if cfg.ShouldApplyPtr("score", d.Score) && d.Score != nil {
		c = c.SetScore(*d.Score)
	}
	if cfg.ShouldApply("external_id", d.ExternalID) {
		c = c.SetExternalID(d.ExternalID)
	}
	if cfg.ShouldApplyPtr("updated_at", d.UpdatedAt) && d.UpdatedAt != nil {
		c = c.SetUpdatedAt(*d.UpdatedAt)
	}
	if cfg.ShouldApply("settings", d.Settings) {
		c = c.SetSettings(d.Settings)
	}
	if cfg.ShouldApply("labels", d.Labels) {
		c = c.SetLabels(d.Labels)
	}
	if cfg.ShouldApply("tag_names", d.TagNames) {
		c = c.SetTagNames(d.TagNames)
	}
	if cfg.ShouldApply("metadata", d.Metadata) {
		c = c.SetMetadata(d.Metadata)
	}
	if len(d.PostIDs) > 0 {
		c = c.AddPostIDs(d.PostIDs...)
	}
	if len(d.TagIDs) > 0 {
		c = c.AddTagIDs(d.TagIDs...)
	}
	if UserTransformer != nil && UserTransformer.SetFullNameOnCreate != nil {
		UserTransformer.SetFullNameOnCreate(c, d.FullName)
	}
	if UserTransformer != nil && UserTransformer.SetIsPremiumOnCreate != nil {
		UserTransformer.SetIsPremiumOnCreate(c, d.IsPremium)
	}
	if UserTransformer != nil && UserTransformer.SetExpiresAtOnCreate != nil {
		UserTransformer.SetExpiresAtOnCreate(c, d.ExpiresAt)
	}
	if UserTransformer != nil && UserTransformer.SetSubscriptionDurationOnCreate != nil {
		UserTransformer.SetSubscriptionDurationOnCreate(c, d.SubscriptionDuration)
	}
	return c
}

// ApplyDomain applies domain.User fields to the UserUpdateOne builder.
func (u *UserUpdateOne) ApplyDomain(d *domain.User, opts ...entdomain.ApplyOption) *UserUpdateOne {
	cfg := entdomain.NewApplyConfig(opts...)
	_ = cfg
	if cfg.ShouldApply("name", d.Name) {
		u = u.SetName(d.Name)
	}
	if cfg.ShouldApplyPtr("bio", d.Bio) && d.Bio != nil {
		u = u.SetBio(*d.Bio)
	}
	if cfg.ShouldApply("status", d.Status) {
		u = u.SetStatus(user.Status(d.Status))
	}
	if cfg.ShouldApplyPtr("score", d.Score) && d.Score != nil {
		u = u.SetScore(*d.Score)
	}
	if cfg.ShouldApply("external_id", d.ExternalID) {
		u = u.SetExternalID(d.ExternalID)
	}
	if cfg.ShouldApplyPtr("updated_at", d.UpdatedAt) && d.UpdatedAt != nil {
		u = u.SetUpdatedAt(*d.UpdatedAt)
	}
	if cfg.ShouldApply("settings", d.Settings) {
		u = u.SetSettings(d.Settings)
	}
	if cfg.ShouldApply("labels", d.Labels) {
		u = u.SetLabels(d.Labels)
	}
	if cfg.ShouldApply("tag_names", d.TagNames) {
		u = u.SetTagNames(d.TagNames)
	}
	if cfg.ShouldApply("metadata", d.Metadata) {
		u = u.SetMetadata(d.Metadata)
	}
	if cfg.IsAppendEdge("post_ids") {
		u = u.AddPostIDs(d.PostIDs...)
	} else {
		u = u.ClearPosts().AddPostIDs(d.PostIDs...)
	}
	if cfg.IsAppendEdge("tag_ids") {
		u = u.AddTagIDs(d.TagIDs...)
	} else {
		u = u.ClearTags().AddTagIDs(d.TagIDs...)
	}
	if UserTransformer != nil && UserTransformer.SetFullNameOnUpdate != nil {
		UserTransformer.SetFullNameOnUpdate(u, d.FullName)
	}
	if UserTransformer != nil && UserTransformer.SetIsPremiumOnUpdate != nil {
		UserTransformer.SetIsPremiumOnUpdate(u, d.IsPremium)
	}
	if UserTransformer != nil && UserTransformer.SetExpiresAtOnUpdate != nil {
		UserTransformer.SetExpiresAtOnUpdate(u, d.ExpiresAt)
	}
	if UserTransformer != nil && UserTransformer.SetSubscriptionDurationOnUpdate != nil {
		UserTransformer.SetSubscriptionDurationOnUpdate(u, d.SubscriptionDuration)
	}
	return u
}

// ApplyDomain applies domain.User fields to the UserUpdate builder.
// Chain .Where(...) conditions to target specific records.
func (u *UserUpdate) ApplyDomain(d *domain.User, opts ...entdomain.ApplyOption) *UserUpdate {
	cfg := entdomain.NewApplyConfig(opts...)
	_ = cfg
	if cfg.ShouldApply("name", d.Name) {
		u = u.SetName(d.Name)
	}
	if cfg.ShouldApplyPtr("bio", d.Bio) && d.Bio != nil {
		u = u.SetBio(*d.Bio)
	}
	if cfg.ShouldApply("status", d.Status) {
		u = u.SetStatus(user.Status(d.Status))
	}
	if cfg.ShouldApplyPtr("score", d.Score) && d.Score != nil {
		u = u.SetScore(*d.Score)
	}
	if cfg.ShouldApply("external_id", d.ExternalID) {
		u = u.SetExternalID(d.ExternalID)
	}
	if cfg.ShouldApplyPtr("updated_at", d.UpdatedAt) && d.UpdatedAt != nil {
		u = u.SetUpdatedAt(*d.UpdatedAt)
	}
	if cfg.ShouldApply("settings", d.Settings) {
		u = u.SetSettings(d.Settings)
	}
	if cfg.ShouldApply("labels", d.Labels) {
		u = u.SetLabels(d.Labels)
	}
	if cfg.ShouldApply("tag_names", d.TagNames) {
		u = u.SetTagNames(d.TagNames)
	}
	if cfg.ShouldApply("metadata", d.Metadata) {
		u = u.SetMetadata(d.Metadata)
	}
	if cfg.IsAppendEdge("post_ids") {
		u = u.AddPostIDs(d.PostIDs...)
	} else {
		u = u.ClearPosts().AddPostIDs(d.PostIDs...)
	}
	if cfg.IsAppendEdge("tag_ids") {
		u = u.AddTagIDs(d.TagIDs...)
	} else {
		u = u.ClearTags().AddTagIDs(d.TagIDs...)
	}
	return u
}

// ApplyDomain applies domain.User fields to the UserUpsertOne builder on conflict.
func (u *UserUpsertOne) ApplyDomain(d *domain.User, opts ...entdomain.ApplyOption) *UserUpsertOne {
	cfg := entdomain.NewApplyConfig(opts...)
	_ = cfg
	return u.Update(func(uu *UserUpsert) {
		if cfg.ShouldApply("name", d.Name) {
			uu.SetName(d.Name)
		}
		if cfg.ShouldApplyPtr("bio", d.Bio) && d.Bio != nil {
			uu.SetBio(*d.Bio)
		}
		if cfg.ShouldApply("status", d.Status) {
			uu.SetStatus(user.Status(d.Status))
		}
		if cfg.ShouldApplyPtr("score", d.Score) && d.Score != nil {
			uu.SetScore(*d.Score)
		}
		if cfg.ShouldApply("external_id", d.ExternalID) {
			uu.SetExternalID(d.ExternalID)
		}
		if cfg.ShouldApplyPtr("updated_at", d.UpdatedAt) && d.UpdatedAt != nil {
			uu.SetUpdatedAt(*d.UpdatedAt)
		}
		if cfg.ShouldApply("settings", d.Settings) {
			uu.SetSettings(d.Settings)
		}
		if cfg.ShouldApply("labels", d.Labels) {
			uu.SetLabels(d.Labels)
		}
		if cfg.ShouldApply("tag_names", d.TagNames) {
			uu.SetTagNames(d.TagNames)
		}
		if cfg.ShouldApply("metadata", d.Metadata) {
			uu.SetMetadata(d.Metadata)
		}
	})
}

// ApplyDomain applies domain.User fields to the UserUpsertBulk builder on conflict.
func (u *UserUpsertBulk) ApplyDomain(d *domain.User, opts ...entdomain.ApplyOption) *UserUpsertBulk {
	cfg := entdomain.NewApplyConfig(opts...)
	_ = cfg
	return u.Update(func(uu *UserUpsert) {
		if cfg.ShouldApply("name", d.Name) {
			uu.SetName(d.Name)
		}
		if cfg.ShouldApplyPtr("bio", d.Bio) && d.Bio != nil {
			uu.SetBio(*d.Bio)
		}
		if cfg.ShouldApply("status", d.Status) {
			uu.SetStatus(user.Status(d.Status))
		}
		if cfg.ShouldApplyPtr("score", d.Score) && d.Score != nil {
			uu.SetScore(*d.Score)
		}
		if cfg.ShouldApply("external_id", d.ExternalID) {
			uu.SetExternalID(d.ExternalID)
		}
		if cfg.ShouldApplyPtr("updated_at", d.UpdatedAt) && d.UpdatedAt != nil {
			uu.SetUpdatedAt(*d.UpdatedAt)
		}
		if cfg.ShouldApply("settings", d.Settings) {
			uu.SetSettings(d.Settings)
		}
		if cfg.ShouldApply("labels", d.Labels) {
			uu.SetLabels(d.Labels)
		}
		if cfg.ShouldApply("tag_names", d.TagNames) {
			uu.SetTagNames(d.TagNames)
		}
		if cfg.ShouldApply("metadata", d.Metadata) {
			uu.SetMetadata(d.Metadata)
		}
	})
}

// ToDomain maps a slice of ent User to domain.UserList.
func (es Users) ToDomain() domain.UserList {
	ds := make(domain.UserList, len(es))
	for i, e := range es {
		ds[i] = e.ToDomain()
	}
	return ds
}

// CreateBulkDomain creates a UserCreateBulk from domain.UserList.
func (c *UserClient) CreateBulkDomain(ds domain.UserList, opts ...entdomain.ApplyOption) *UserCreateBulk {
	builders := make([]*UserCreate, len(ds))
	for i := range ds {
		builders[i] = c.Create().ApplyDomain(ds[i], opts...)
	}
	return c.CreateBulk(builders...)
}

// UserUpdateOneBulk holds a set of UserUpdateOne builders.
type UserUpdateOneBulk struct {
	builders []*UserUpdateOne
}

// Save executes all builders and returns the updated entities as domain.UserList.
func (b *UserUpdateOneBulk) Save(ctx context.Context) (domain.UserList, error) {
	result := make(domain.UserList, 0, len(b.builders))
	for _, builder := range b.builders {
		updated, err := builder.Save(ctx)
		if err != nil {
			return nil, err
		}
		result = append(result, updated.ToDomain())
	}
	return result, nil
}

// SaveX is like Save but panics on error.
func (b *UserUpdateOneBulk) SaveX(ctx context.Context) domain.UserList {
	result, err := b.Save(ctx)
	if err != nil {
		panic(err)
	}
	return result
}

// Exec executes all builders without returning the updated entities.
func (b *UserUpdateOneBulk) Exec(ctx context.Context) error {
	_, err := b.Save(ctx)
	return err
}

// ExecX is like Exec but panics on error.
func (b *UserUpdateOneBulk) ExecX(ctx context.Context) {
	if err := b.Exec(ctx); err != nil {
		panic(err)
	}
}

// UpdateBulkDomain returns a UserUpdateOneBulk from domain.UserList.
// Each builder is keyed on ds[i].ID.
func (c *UserClient) UpdateBulkDomain(ds domain.UserList, opts ...entdomain.ApplyOption) *UserUpdateOneBulk {
	builders := make([]*UserUpdateOne, len(ds))
	for i := range ds {
		builders[i] = c.UpdateOneID(ds[i].ID).ApplyDomain(ds[i], opts...)
	}
	return &UserUpdateOneBulk{builders: builders}
}
