// Code generated by ent, DO NOT EDIT.

package ent

import (
	"github.com/danhtran94/entdomain"
	"github.com/danhtran94/entdomain/examples/basic/ent/predicate"
	"github.com/danhtran94/entdomain/examples/basic/ent/user"
)

// UserFIQLFields is the FIQL field registry for User.
// Pass it to entdomain.ParseFIQL to filter User entities.
var UserFIQLFields = entdomain.FIQLFields[predicate.User]{
	"name": entdomain.FIQLString[predicate.User]{
		EQ:       user.NameEQ,
		NEQ:      user.NameNEQ,
		Contains: user.NameContains,
	},
	"status": entdomain.FIQLEnum[predicate.User]{
		EQ: map[string]predicate.User{
			"active":   user.StatusEQ(user.StatusActive),
			"inactive": user.StatusEQ(user.StatusInactive),
		},
		NEQ: map[string]predicate.User{
			"active":   user.StatusNEQ(user.StatusActive),
			"inactive": user.StatusNEQ(user.StatusInactive),
		},
	},
	"created_at": entdomain.FIQLTime[predicate.User]{
		GTE: user.CreatedAtGTE,
		LTE: user.CreatedAtLTE,
	},
	"score": entdomain.FIQLInt[predicate.User]{
		EQ:  user.ScoreEQ,
		GT:  user.ScoreGT,
		LT:  user.ScoreLT,
		GTE: user.ScoreGTE,
		LTE: user.ScoreLTE,
	},
	"external_id": entdomain.FIQLUUID[predicate.User]{
		EQ:  user.ExternalIDEQ,
		NEQ: user.ExternalIDNEQ,
	},
}

// UserFIQL parses a FIQL filter expression and returns an ent predicate
// for querying User entities.
//
// Example:
//
//	pred, err := ent.UserFIQL("name==john;age=gt=25")
//	users, err := client.User.Query().Where(pred).All(ctx)
func UserFIQL(expr string) (predicate.User, error) {
	return entdomain.ParseFIQL(expr, UserFIQLFields)
}
